FUNCTION Z_AW_TREE_IMPORT40.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(P_LANG) LIKE  DD04T-DDLANGUAGE
*"             VALUE(P_TREEAREA) LIKE  DD02D-DDTEXT
*"             VALUE(P_TREEGROUP) LIKE  DD04L-ROLLNAME
*"             VALUE(P_TREETABLE) LIKE  DD02D-TABNAME
*"       EXPORTING
*"             VALUE(DESCRIPTION) LIKE  DD04T-DDTEXT
*"             VALUE(CONTROLLING_AREA) LIKE  DD02D-DDTEXT
*"             VALUE(CHART_OF_ACCT) LIKE  DD02D-DDTEXT
*"             VALUE(TABLE_NAME) LIKE  DD02D-TABNAME
*"             VALUE(FIELD_NAME) LIKE  DD03D-FIELDNAME
*"             VALUE(DOMAIN_NAME) LIKE  DD03L-DOMNAME
*"             VALUE(CHECK_TABLE) LIKE  DD03L-CHECKTABLE
*"             VALUE(CONT_AREA_LIST) LIKE  TAB512-WA
*"       TABLES
*"              COLUMNS STRUCTURE  LISTZEILE
*"----------------------------------------------------------------------

statics pn like sy-cprog.

DATA: codetab(72) occurs 10 with header line,
      ln type i, msg(128),
      L_TABNAME LIKE DD02L-TABNAME,
      L_RC LIKE SY-SUBRC,
      lf_sap_release type i.

move sy-saprl(1) to lf_sap_release.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'T800S' AND AS4LOCAL = 'A'.
ENDSELECT.

L_RC = SY-SUBRC.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'SETHEADER' AND AS4LOCAL = 'A'.
ENDSELECT.

IF SY-SUBRC <> 0 OR L_RC <> 0 OR lf_sap_release < 4.
   EXIT.
ENDIF.

if PN(2) <> '%_'.
   APPEND 'REPORT ZWATI4.' TO CODETAB.
   APPEND 'FORM Z_AW_TREE_IMPORT40_FORM' TO CODETAB.
   APPEND '       TABLES' TO CODETAB.
   APPEND '              COLUMNS STRUCTURE  LISTZEILE' TO CODETAB.
   APPEND '       USING' TO CODETAB.
   APPEND '            P_LANG LIKE  DD04T-DDLANGUAGE' TO CODETAB.
   APPEND '            P_TREEAREA1 LIKE  DD02D-DDTEXT' TO CODETAB.
   APPEND '            P_TREEGROUP1 LIKE  DD04L-ROLLNAME' TO CODETAB.
   APPEND '            P_TREETABLE1 LIKE  DD02D-TABNAME' TO CODETAB.
   APPEND '       CHANGING' TO CODETAB.
   APPEND '            DESCRIPTION LIKE  DD04T-DDTEXT' TO CODETAB.
   APPEND '            CONTROLLING_AREA1 LIKE  DD02D-DDTEXT' TO CODETAB.
   APPEND '            CHART_OF_ACCT1 LIKE  DD02D-DDTEXT' TO CODETAB.
   APPEND '            TABLE_NAME1 LIKE  DD02D-TABNAME' TO CODETAB.
   APPEND '            FIELD_NAME1 LIKE  DD03D-FIELDNAME' TO CODETAB.
   APPEND '            DOMAIN_NAME1 LIKE  DD03L-DOMNAME' TO CODETAB.
   APPEND '            CHECK_TABLE1 LIKE  DD03L-CHECKTABLE' TO CODETAB.
   APPEND '            CONT_AREA_LIST LIKE  TAB512-WA.'
     TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'TABLES: DD02T, DD03L, DD04T, DD01L, T800S, TKA01, SETHEADER.'
     TO CODETAB.

   APPEND 'DATA:       P_TREEAREA LIKE  SETHEADER-SUBCLASS,' TO CODETAB.
   APPEND '            P_TREEGROUP LIKE  DD04L-ROLLNAME,' TO CODETAB.
   APPEND '            P_TREETABLE LIKE  SETHEADER-TABNAME,' TO CODETAB.
   APPEND '            CONTROLLING_AREA LIKE  TKA01-KOKRS,' TO CODETAB.
   APPEND '            CHART_OF_ACCT LIKE  TKA01-KTOPL,' TO CODETAB.
   APPEND '            TABLE_NAME LIKE  T800S-TAB,' TO CODETAB.
   APPEND '            FIELD_NAME LIKE  T800S-FELD,' TO CODETAB.
   APPEND '            DOMAIN_NAME LIKE  DD03L-DOMNAME,' TO CODETAB.
   APPEND '            CHECK_TABLE LIKE  DD03L-CHECKTABLE.' TO CODETAB.

   APPEND '       P_TREEAREA = P_TREEAREA1.' TO CODETAB.
   APPEND '       P_TREEGROUP = P_TREEGROUP1.' TO CODETAB.
   APPEND '       P_TREETABLE = P_TREETABLE1.' TO CODETAB.
   APPEND '       CONTROLLING_AREA = CONTROLLING_AREA1.' TO CODETAB.
   APPEND '       CHART_OF_ACCT = CHART_OF_ACCT1.' TO CODETAB.
   APPEND '       TABLE_NAME = TABLE_NAME1.' TO CODETAB.
   APPEND '       FIELD_NAME = FIELD_NAME1.' TO CODETAB.
   APPEND '       DOMAIN_NAME = DOMAIN_NAME1.' TO CODETAB.
   APPEND '       CHECK_TABLE = CHECK_TABLE1.' TO CODETAB.

   APPEND 'SELECT SINGLE * FROM DD02T' TO CODETAB.
   APPEND ' WHERE TABNAME = P_TREETABLE' TO CODETAB.
   APPEND '   AND DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND 'IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '  CONCATENATE DD02T-DDTEXT ''-'' INTO DESCRIPTION.'
     TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND 'SELECT * FROM DD02T UP TO 1 ROWS' TO CODETAB.
   APPEND ' WHERE TABNAME = P_TREETABLE' TO CODETAB.
*   append '   AND DDLANGUAGE = P_LANG' to codetab.
   APPEND '   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '  CONCATENATE DD02T-DDTEXT ''-'' INTO DESCRIPTION.'
     TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND '  WRITE:' TO CODETAB.
   APPEND '    / ''Table not found in DD02T. P_TREETABLE = '','
     TO CODETAB.
   APPEND '    P_TREETABLE.' TO CODETAB.
   APPEND '  EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'SELECT SINGLE * FROM DD03L' TO CODETAB.
   APPEND ' WHERE TABNAME = P_TREETABLE' TO CODETAB.
   APPEND '   AND   FIELDNAME = P_TREEGROUP' TO CODETAB.
   APPEND '   AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '   AND   AS4VERS = ''0000''.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND '  WRITE: / ' TO CODETAB.
   APPEND '         ''Table not found in DD03L. P_TREETABLE = '','
     TO CODETAB.
   APPEND '         P_TREETABLE.' TO CODETAB.
   APPEND '  WRITE: / ''P_TREEGROUP = '', P_TREEGROUP.' TO CODETAB.
   APPEND '  EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'SELECT SINGLE * FROM DD04T' TO CODETAB.
   APPEND ' WHERE ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '   AND DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'SELECT * FROM DD04T UP TO 1 ROWS' TO CODETAB.
   APPEND ' WHERE ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
*   append '   AND DDLANGUAGE = P_LANG' to codetab.
   APPEND '   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND '  WRITE: /' TO CODETAB.
   APPEND '      ''Table description not found in DD04T. P_LANG = '','
     TO CODETAB.
   APPEND '         P_LANG.' TO CODETAB.
   APPEND '  EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'SELECT * FROM DD01L UP TO 1 ROWS' TO CODETAB.
   APPEND ' WHERE DOMNAME = DD03L-DOMNAME' TO CODETAB.
   APPEND '   AND AS4LOCAL = ''A''.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND '  WRITE: /' TO CODETAB.
   APPEND '        ''Domain not found in DD01L. DOMNAME = '','
     TO CODETAB.
   APPEND '        DD03L-DOMNAME.' TO CODETAB.
   APPEND '  EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CHECK_TABLE = DD01L-ENTITYTAB.' TO CODETAB.
   APPEND 'CONCATENATE DESCRIPTION DD04T-DDTEXT' TO CODETAB.
   APPEND '       INTO DESCRIPTION.' TO CODETAB.
   APPEND 'IF ( P_TREEAREA = ''*'' ).' TO CODETAB.
   APPEND '  CONTROLLING_AREA = ''NULL''.' TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND '  CONTROLLING_AREA = P_TREEAREA.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'TABLE_NAME = P_TREETABLE.' TO CODETAB.
   APPEND 'FIELD_NAME = DD03L-FIELDNAME.' TO CODETAB.
   APPEND 'DOMAIN_NAME = DD03L-DOMNAME.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Verify against 4.0 set name' TO CODETAB.
   APPEND 'IF CONTROLLING_AREA = SPACE OR' TO CODETAB.
   APPEND '   CONTROLLING_AREA = ''NULL''.' TO CODETAB.
   APPEND '  CHART_OF_ACCT = ''NULL''.' TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND '  SELECT SINGLE * FROM TKA01' TO CODETAB.
   APPEND '   WHERE KOKRS = CONTROLLING_AREA.' TO CODETAB.
   APPEND '  IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND '    WRITE: / ' TO CODETAB.
   APPEND '       ''Controlling area not found. CONTROLLING_AREA = '','
     TO CODETAB.
   APPEND '           CONTROLLING_AREA.' TO CODETAB.
   APPEND '    EXIT.' TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND '  SELECT * FROM T800S UP TO 1 ROWS' TO CODETAB.
   APPEND '   WHERE TAB = P_TREETABLE' TO CODETAB.
   APPEND '     AND   FELD = P_TREEGROUP' TO CODETAB.
   APPEND '     AND   ( SEARCHFLD = CONTROLLING_AREA' TO CODETAB.
   APPEND '      OR SEARCHFLD = TKA01-KTOPL ).' TO CODETAB.
   APPEND '  ENDSELECT.' TO CODETAB.
   APPEND '  IF SY-DBCNT > 0.' TO CODETAB.
   APPEND '    IF ( CONTROLLING_AREA = T800S-SEARCHFLD ).' TO CODETAB.
   APPEND '      CHART_OF_ACCT = ''NULL''.' TO CODETAB.
   APPEND '    ELSEIF ( TKA01-KTOPL <> SPACE' TO CODETAB.
   APPEND '             AND T800S-SEARCHFLD = TKA01-KTOPL ).'
     TO CODETAB.
   APPEND '      CHART_OF_ACCT = T800S-SEARCHFLD.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '  ELSE.' TO CODETAB.
   APPEND '    SELECT * FROM SETHEADER UP TO 1 ROWS' TO CODETAB.
   APPEND '     WHERE TABNAME = P_TREETABLE' TO CODETAB.
   APPEND '       AND   FIELDNAME = P_TREEGROUP' TO CODETAB.
   APPEND '       AND   ( SUBCLASS = CONTROLLING_AREA' TO CODETAB.
   APPEND '        OR SUBCLASS = TKA01-KTOPL ).' TO CODETAB.
   APPEND '    ENDSELECT.' TO CODETAB.
   APPEND '    IF SY-DBCNT > 0.' TO CODETAB.
   APPEND '      IF ( CONTROLLING_AREA = SETHEADER-SUBCLASS ).'
     TO CODETAB.
   APPEND '        CHART_OF_ACCT = ''NULL''.' TO CODETAB.
   APPEND '   ELSEIF ( TKA01-KTOPL <> SPACE' TO CODETAB.
   APPEND '        AND SETHEADER-SUBCLASS = TKA01-KTOPL ).' TO CODETAB.
   APPEND '        CHART_OF_ACCT = SETHEADER-SUBCLASS.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '    ELSE.' TO CODETAB.
   APPEND '      WRITE: /' TO CODETAB.
   APPEND '        ''Controlling area not found. CONTROLLING_AREA = '','
     TO CODETAB.
   APPEND '             P_TREEAREA.' TO CODETAB.
   APPEND '      EXIT.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CONCATENATE ''*-'' ''All Hierarchies,''' TO CODETAB.
   APPEND '            INTO CONT_AREA_LIST.' TO CODETAB.
   APPEND 'SELECT * FROM TKA01.' TO CODETAB.
   APPEND
  '  CONCATENATE CONT_AREA_LIST TKA01-KOKRS ''-'' TKA01-BEZEI '','''
     TO CODETAB.
   APPEND '              INTO CONT_AREA_LIST.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''1|PARENT_ID|V|30||||Parent node id|''.' TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''2|PARENT_DESC|V|64||||Parent node description|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''3|CHILD_ID|V|30||||Child set id|''.' TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''4|CHILD_DESC|V|64||||Description of child node|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND '  ''5|VALUE_FROM|V|24||||Start of value range|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND '  ''6|VALUE_TO|V|24||||End of value range|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND
 '  ''7|LEAF_FLAG|V|1||||Leaf node indicator (child node is leaf)|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND
  ' ''8|ROOT_FLAG|V|1||||Root node indicator (parent node is root)|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''9|TREE_LEVEL|V|3||||Tree level of current node|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''10|CONTROLLING_AREA|V|30||||Controlling area|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND ' ''11|CHART_OF_ACCT|V|30||||Chart of account|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'COLUMNS-ZEILE =' TO CODETAB.
   APPEND
  ' ''12|P_TREETABLE|V|30||||SAP table that identify a set id|''.'
     TO CODETAB.
   APPEND 'APPEND COLUMNS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM.' TO CODETAB.
   generate subroutine pool CODETAB name pn message msg line ln.
endif.

PERFORM Z_AW_TREE_IMPORT40_FORM IN PROGRAM (pn)
       TABLES
              COLUMNS
       USING
             P_LANG
             P_TREEAREA
             P_TREEGROUP
             P_TREETABLE
       CHANGING
             DESCRIPTION
             CONTROLLING_AREA
             CHART_OF_ACCT
             TABLE_NAME
             FIELD_NAME
             DOMAIN_NAME
             CHECK_TABLE
             CONT_AREA_LIST.

ENDFUNCTION.

FORM Z_AW_TREE_IMPORT40_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
