FUNCTION Z_AW_MODEL_NAVIGATE.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(P_OID) LIKE  DM41S-DMOID
*"             VALUE(P_LANG) LIKE  DD02T-DDLANGUAGE
*"       TABLES
*"              P_RETURN STRUCTURE  LISTZEILE
*"----------------------------------------------------------------------

TABLES: DM41S, DM40T, DM26L.

IF P_OID = 'SAP_DM'.
SELECT *
FROM   DM41S
WHERE  DMOID = P_OID AND OBJID = 'SAP_ANW' AND AS4LOCAL = 'A'.

IF DM41S-OBJTYP = 'E'.

   SELECT *
   FROM   DM26L
   WHERE  ENTID = DM41S-OBJID.
   SELECT *
   FROM   DD02VV
   WHERE  AS4LOCAL   = 'A'
     AND  DDLANGUAGE = P_LANG
     AND  TABNAME    = DM26L-TABNAME
     AND  TABCLASS <> 'APPEND'
     AND  TABCLASS <> 'INTTAB'.

      CONCATENATE
      'T' '|' DD02VV-TABNAME '|' DD02VV-DDTEXT '|'
      INTO P_RETURN-ZEILE.

      APPEND P_RETURN.

   ENDSELECT.
   ENDSELECT.

ELSE.

   SELECT *
   FROM   DM40T
   WHERE  AS4LOCAL = 'A'
     AND  SPRACHE = P_LANG
     AND  DMOID = DM41S-OBJID.

      CONCATENATE
      'D' '|' DM40T-DMOID '|' DM40T-LANGBEZ '|'
      INTO P_RETURN-ZEILE.

      APPEND P_RETURN.

   ENDSELECT.

ENDIF.

ENDSELECT.
ELSE.
SELECT *
FROM   DM41S
WHERE  DMOID = P_OID AND AS4LOCAL = 'A'.

IF DM41S-OBJTYP = 'E'.

   SELECT *
   FROM   DM26L
   WHERE  ENTID = DM41S-OBJID.
   SELECT *
   FROM   DD02VV
   WHERE  AS4LOCAL   = 'A'
     AND  DDLANGUAGE = P_LANG
     AND  TABNAME    = DM26L-TABNAME
     AND  TABCLASS <> 'APPEND'
     AND  TABCLASS <> 'INTTAB'.

      CONCATENATE
      'T' '|' DD02VV-TABNAME '|' DD02VV-DDTEXT '|'
      INTO P_RETURN-ZEILE.

      APPEND P_RETURN.

   ENDSELECT.
   ENDSELECT.

ELSE.

   SELECT *
   FROM   DM40T
   WHERE  AS4LOCAL = 'A'
     AND  SPRACHE = P_LANG
     AND  DMOID = DM41S-OBJID.

      CONCATENATE
      'D' '|' DM40T-DMOID '|' DM40T-LANGBEZ '|'
      INTO P_RETURN-ZEILE.

      APPEND P_RETURN.

   ENDSELECT.

ENDIF.

ENDSELECT.
ENDIF.

ENDFUNCTION.

FORM Z_AW_MODEL_NAVIGATE_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
