FUNCTION Z_AW_TABLE_IMPORT.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(TABNAME) LIKE  DD03L-TABNAME
*"             VALUE(LANG) LIKE  DD02T-DDLANGUAGE
*"       EXPORTING
*"             VALUE(DESCRIPTION) LIKE  DD02T-DDTEXT
*"             VALUE(TABCLASS) LIKE  DD02L-TABCLASS
*"       TABLES
*"              COLUMNS STRUCTURE  LISTZEILE
*"              INDEXES STRUCTURE  LISTZEILE
*"              FKEYS STRUCTURE  LISTZEILE
*"       EXCEPTIONS
*"              NO_TABLECLASS_FOR_TABLE
*"----------------------------------------------------------------------
* DATA POSITION LIKE DD03L-POSITION.

SELECT TABCLASS INTO TABCLASS FROM DD02L UP TO 1 ROWS
    WHERE AS4LOCAL = 'A'
      AND TABNAME = TABNAME.
 ENDSELECT.
 IF SY-SUBRC <> 0.
    RAISE NO_TABLECLASS_FOR_TABLE.
 ENDIF.
* for view, the description is in table dd25t. see bug#8492
IF TABCLASS = 'VIEW'.
  SELECT DDTEXT INTO DESCRIPTION FROM DD25T UP TO 1 ROWS
  WHERE AS4LOCAL = 'A'
    AND DDLANGUAGE = LANG
    AND VIEWNAME = TABNAME.
ENDSELECT.
ELSE.
  SELECT DDTEXT INTO DESCRIPTION FROM DD02T UP TO 1 ROWS
  WHERE AS4LOCAL = 'A'
    AND DDLANGUAGE = LANG
    AND TABNAME = TABNAME.
  ENDSELECT.
ENDIF.
"if sy-subrc <> 0.
"   raise no_desciption_for_table.
"endif.

SELECT * FROM DD03L
       WHERE AS4LOCAL = 'A'
       AND   FIELDNAME NOT LIKE '.INCLU%'
       AND   TABNAME = TABNAME ORDER BY POSITION.
SELECT SINGLE * FROM DD04T
       WHERE DDLANGUAGE = 'E'
       AND   AS4VERS  = DD03L-AS4VERS
       AND   AS4LOCAL = DD03L-AS4LOCAL
       AND   ROLLNAME = DD03L-ROLLNAME.

if sy-subrc <> 0.
SELECT * FROM DD04T UP TO 1 ROWS
       WHERE DDLANGUAGE = 'E'
       AND   AS4LOCAL = DD03L-AS4LOCAL
       AND   ROLLNAME = DD03L-ROLLNAME.
ENDSELECT.
ENDIF.
* POSITION = POSITION + 1.
CONCATENATE
*  POSITION '|'
  DD03L-POSITION '|'
  DD03L-FIELDNAME '|'
  DD03L-INTTYPE '|'
  DD03L-LENG '|'
  DD03L-DECIMALS '|'
  DD03L-NOTNULL '|'
  DD03L-KEYFLAG '|'
  DD04T-DDTEXT '|'
  DD03L-DATATYPE '|'
 INTO COLUMNS-ZEILE.

  APPEND COLUMNS.
ENDSELECT.

*DATA: D_PRIMPOS LIKE DD05S-PRIMPOS,
*      D_FIELDNAME LIKE DD03L-FIELDNAME.
TABLES: DD05S.

DATA: D_FORKEY LIKE DD05S-FORKEY,
      KEY_SEQ TYPE I VALUE 1,
      KEY_SEQ_S(10).

SELECT CHECKTABLE FIELDNAME CARD
INTO CORRESPONDING FIELDS OF DD08L
   FROM DD08L
   WHERE AS4LOCAL = 'A'
     AND TABNAME = TABNAME
   ORDER BY CHECKTABLE FIELDNAME.

* SELECT * FROM DD08L
*    WHERE AS4LOCAL = 'A'
*      AND TABNAME = TABNAME.

IF DD08L-CHECKTABLE <> '*'.
*SELECT *
*FROM DD05S
*WHERE TABNAME = TABNAME
*  AND FIELDNAME = DD08L-FIELDNAME
*  AND AS4LOCAL = 'A'.
*
*SELECT *
*FROM DD03L
*WHERE TABNAME = DD08L-CHECKTABLE
*  AND POSITION = DD05S-PRIMPOS
*  AND AS4LOCAL = 'A'.

KEY_SEQ = 1.
SELECT FORKEY FIELDNAME PRIMPOS FORTABLE
INTO CORRESPONDING FIELDS OF DD05S
FROM DD05S
WHERE TABNAME = TABNAME
  AND FIELDNAME = DD08L-FIELDNAME
  AND AS4LOCAL = 'A'
  AND FORKEY <> 'MANDT'
ORDER BY PRIMPOS.

SELECT FIELDNAME
INTO CORRESPONDING FIELDS OF DD03L
FROM DD03L
WHERE TABNAME = DD08L-CHECKTABLE
  AND POSITION = DD05S-PRIMPOS
  AND AS4LOCAL = 'A'.

  IF DD05S-FORKEY IS INITIAL.
    D_FORKEY = DD05S-FORTABLE.
  ELSE.
    D_FORKEY = DD05S-FORKEY.
  ENDIF.

  WRITE KEY_SEQ TO KEY_SEQ_S.
  CONDENSE KEY_SEQ_S NO-GAPS.
   CONCATENATE
     D_FORKEY '|'
     DD08L-CHECKTABLE '|'
     DD03L-FIELDNAME '|'
     DD08L-CARD '|'
      KEY_SEQ_S '|'
   INTO FKEYS-ZEILE.

   APPEND FKEYS.
    KEY_SEQ = KEY_SEQ + 1.
 ENDSELECT.
 ENDSELECT.

 ENDIF.
 ENDSELECT.
DATA OLDINDEX LIKE DD17S-INDEXNAME.
DATA POS LIKE DD17S-POSITION.
DATA LESS1 TYPE I.

 SELECT * FROM DD17S
     WHERE AS4LOCAL = 'A'
     AND   SQLTAB = TABNAME
     ORDER BY INDEXNAME.
 IF OLDINDEX <> DD17S-INDEXNAME. LESS1 = 0. ENDIF.
 IF DD17S-FIELDNAME = 'MANDT'.   LESS1 = 1. ENDIF.
 IF LESS1 = 1. POS = DD17S-POSITION - 1.
 ELSE.         POS = DD17S-POSITION. ENDIF.
 IF DD17S-FIELDNAME <> 'MANDT'.
   CONCATENATE
     DD17S-INDEXNAME '|'
     DD17S-FIELDNAME '|'
     POS '|'
   INTO INDEXES-ZEILE.

 APPEND INDEXES.
 ENDIF.
 OLDINDEX = DD17S-INDEXNAME.
ENDSELECT.

ENDFUNCTION.

FORM Z_AW_TABLE_IMPORT_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
