FUNCTION Z_AW_TREE_SEARCH.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(TREENAME) LIKE  DD08T-MESTEXT
*"             VALUE(TREEDESC) LIKE  DD04T-DDTEXT
*"             VALUE(LANG) LIKE  SY-LANGU
*"             VALUE(MAX_ROWS) LIKE  SY-TABIX
*"             VALUE(FLAG) LIKE  SY-TABIX
*"       TABLES
*"              P_RETURN STRUCTURE  LISTZEILE
*"----------------------------------------------------------------------

statics pn like sy-cprog.

DATA: codetab(72) occurs 10 with header line,
      ln type i, msg(128),
      L_TABNAME LIKE DD02L-TABNAME,
      L_RC LIKE SY-SUBRC,
      lf_sap_release type i.

move sy-saprl(1) to lf_sap_release.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'T800S' AND AS4LOCAL = 'A'.
ENDSELECT.

L_RC = SY-SUBRC.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'TKA01' AND AS4LOCAL = 'A'.
ENDSELECT.

IF SY-SUBRC <> 0 OR L_RC <> 0 OR lf_sap_release > 3.
   EXIT.
ENDIF.

if PN(2) <> '%_'.
   APPEND 'REPORT ZWATS3.' TO CODETAB.
   APPEND 'TABLES: DD02T, DD03L, DD04T.' TO CODETAB.
   APPEND 'FORM Z_AW_TREE_SEARCH_FORM' TO CODETAB.
   APPEND '       TABLES' TO CODETAB.
   APPEND '             P_RETURN STRUCTURE  LISTZEILE' TO CODETAB.
   APPEND '       USING' TO CODETAB.
   APPEND '             TREENAME1 LIKE  DD08T-MESTEXT' TO CODETAB.
   APPEND '             TREEDESC LIKE  DD04T-DDTEXT' TO CODETAB.
   APPEND '             LANG LIKE  SY-LANGU' TO CODETAB.
   APPEND '             MAX_ROWS LIKE  SY-TABIX' TO CODETAB.
   APPEND '             FLAG LIKE  SY-TABIX.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'TABLES: TKA01, T800S.' TO CODETAB.
   APPEND 'DATA TREENAME LIKE  PAHI-PARNAME.' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_TREE OCCURS 0,' TO CODETAB.
   APPEND 'TNAME(60),' TO CODETAB.
   APPEND 'TDESC(60).' TO CODETAB.
   APPEND 'DATA: END OF ITAB_TREE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_TREE2 OCCURS 0,' TO CODETAB.
   APPEND 'TNAME(60),' TO CODETAB.
   APPEND 'TDESC(60).' TO CODETAB.
   APPEND 'DATA: END OF ITAB_TREE2.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: NO_ROWS TYPE I.' TO CODETAB.
   APPEND 'DATA: SETNAME LIKE RGSBS-SETNR,' TO CODETAB.
   APPEND '      TABNAME LIKE RGSBS-TABLE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_SUPERSETS OCCURS 0.' TO CODETAB.
   APPEND '        INCLUDE STRUCTURE SETLIST.' TO CODETAB.
   APPEND 'DATA: END OF ITAB_SUPERSETS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND ' TREENAME = TREENAME1.' TO CODETAB.
   APPEND '* Trees without controlling area' TO CODETAB.
   APPEND 'SELECT * FROM T800S' TO CODETAB.
   APPEND '   WHERE SEARCHFLD = SPACE' TO CODETAB.
   APPEND '     AND   ( TYPE = ''S'' OR TYPE = ''B'' ).' TO CODETAB.
   APPEND '  SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '  TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '  CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '       EXPORTING' TO CODETAB.
   APPEND '*             CLIENT    = SY-MANDT' TO CODETAB.
   APPEND '*             SETCLASS  = '' ''' TO CODETAB.
   APPEND '            SETNAME   = SETNAME' TO CODETAB.
   APPEND '            TABNAME   = TABNAME' TO CODETAB.
   APPEND '       TABLES' TO CODETAB.
   APPEND '            SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '       EXCEPTIONS' TO CODETAB.
   APPEND '            OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '  DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.' TO CODETAB.
   APPEND '  IF NO_ROWS = 0.' TO CODETAB.
   APPEND '    CONCATENATE ''*-''' TO CODETAB.
   APPEND '                T800S-TAB ''-''' TO CODETAB.
   APPEND '                T800S-FELD' TO CODETAB.
   APPEND '    INTO ITAB_TREE-TNAME.' TO CODETAB.
   APPEND '    ITAB_TREE-TDESC = SPACE.' TO CODETAB.
   APPEND '    SELECT SINGLE * FROM DD02T' TO CODETAB.
   APPEND '     WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '       AND   DDLANGUAGE = LANG' TO CODETAB.
   APPEND '       AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '       AND   AS4VERS = ''0000''.' TO CODETAB.
   APPEND '    IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '      ITAB_TREE-TDESC = DD02T-DDTEXT.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '    SELECT SINGLE * FROM DD03L' TO CODETAB.
   APPEND '     WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '       AND   FIELDNAME = T800S-FELD' TO CODETAB.
   APPEND '       AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '       AND   AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '    IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '      SELECT SINGLE * FROM DD04T' TO CODETAB.
   APPEND '       WHERE DDLANGUAGE = LANG' TO CODETAB.
   APPEND '         AND   ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '         AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '         AND   AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '      IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '        CONCATENATE ITAB_TREE-TDESC ''-''' TO CODETAB.
   APPEND '                    DD04T-DDTEXT' TO CODETAB.
   APPEND '                    INTO ITAB_TREE-TDESC.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '      APPEND ITAB_TREE.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT * FROM TKA01.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '  SELECT * FROM T800S' TO CODETAB.
   APPEND '   WHERE ( SEARCHFLD = TKA01-KOKRS' TO CODETAB.
   APPEND '      OR    SEARCHFLD = TKA01-KTOPL )' TO CODETAB.
   APPEND '     AND   ( TYPE = ''S'' OR TYPE = ''B'' )' TO CODETAB.
   APPEND '     AND   SETNR LIKE ''0H%''.' TO CODETAB.
   APPEND '    SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '    TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '         EXPORTING' TO CODETAB.
   APPEND '*             CLIENT    = SY-MANDT' TO CODETAB.
   APPEND '*             SETCLASS  = '' ''' TO CODETAB.
   APPEND '              SETNAME   = SETNAME' TO CODETAB.
   APPEND '              TABNAME   = TABNAME' TO CODETAB.
   APPEND '         TABLES' TO CODETAB.
   APPEND '              SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '         EXCEPTIONS' TO CODETAB.
   APPEND '              OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.' TO CODETAB.
   APPEND '    IF NO_ROWS = 0.' TO CODETAB.
   APPEND '      CONCATENATE TKA01-KOKRS ''-''' TO CODETAB.
   APPEND '                  T800S-TAB ''-''' TO CODETAB.
   APPEND '                  T800S-FELD' TO CODETAB.
   APPEND '      INTO ITAB_TREE-TNAME.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      ITAB_TREE-TDESC = SPACE.' TO CODETAB.
   APPEND '      SELECT SINGLE * FROM DD02T' TO CODETAB.
   APPEND '       WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '         AND   DDLANGUAGE = LANG' TO CODETAB.
   APPEND '         AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '         AND   AS4VERS = ''0000''.' TO CODETAB.
   APPEND '      IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '        ITAB_TREE-TDESC = DD02T-DDTEXT.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '      SELECT SINGLE * FROM DD03L' TO CODETAB.
   APPEND '       WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '         AND   FIELDNAME = T800S-FELD' TO CODETAB.
   APPEND '         AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '         AND   AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '      IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '        SELECT SINGLE * FROM DD04T' TO CODETAB.
   APPEND '         WHERE DDLANGUAGE = LANG' TO CODETAB.
   APPEND '           AND   ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '           AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '           AND   AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          CONCATENATE ITAB_TREE-TDESC' TO CODETAB.
   APPEND '                      ''-'' DD04T-DDTEXT' TO CODETAB.
   APPEND '                      INTO ITAB_TREE-TDESC.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '        APPEND ITAB_TREE.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '  ENDSELECT.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SORT ITAB_TREE BY TNAME.' TO CODETAB.
   APPEND 'DELETE ADJACENT DUPLICATES FROM ITAB_TREE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'LOOP AT ITAB_TREE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '  IF FLAG = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    IF ( ITAB_TREE-TNAME CS TREENAME ) AND' TO CODETAB.
   APPEND '       ( ITAB_TREE-TDESC CS TREEDESC ).' TO CODETAB.
   APPEND '      ITAB_TREE2 = ITAB_TREE.' TO CODETAB.
   APPEND '      APPEND ITAB_TREE2.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '  ELSE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    IF ( TREENAME <> SPACE ).' TO CODETAB.
   APPEND '      IF ( TREEDESC <> SPACE ).' TO CODETAB.
   APPEND '        IF ( ITAB_TREE-TNAME = TREENAME ) AND' TO CODETAB.
   APPEND '           ( ITAB_TREE-TDESC = TREEDESC ).' TO CODETAB.
   APPEND '          ITAB_TREE2 = ITAB_TREE.' TO CODETAB.
   APPEND '          APPEND ITAB_TREE2.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '      ELSE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '        IF ( ITAB_TREE-TNAME = TREENAME ).' TO CODETAB.
   APPEND '          ITAB_TREE2 = ITAB_TREE.' TO CODETAB.
   APPEND '          APPEND ITAB_TREE2.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND 'ENDLOOP.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'LOOP AT ITAB_TREE2.' TO CODETAB.
   APPEND '  CONCATENATE ITAB_TREE2-TNAME ''|''' TO CODETAB.
   APPEND '           ITAB_TREE2-TDESC ''|''' TO CODETAB.
   APPEND '   INTO P_RETURN-ZEILE.' TO CODETAB.
   APPEND '  CONDENSE ITAB_TREE2 NO-GAPS.' TO CODETAB.
   APPEND '  APPEND P_RETURN.' TO CODETAB.
   APPEND 'ENDLOOP.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM.' TO CODETAB.
   generate subroutine pool CODETAB name pn message msg line ln.
endif.

PERFORM Z_AW_TREE_SEARCH_FORM IN PROGRAM (pn)
       TABLES
             P_RETURN
       USING
             TREENAME
             TREEDESC
             LANG
             MAX_ROWS
             FLAG.

ENDFUNCTION.

FORM Z_AW_TREE_SEARCH_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
