FUNCTION Z_AW_TREE_NAVIGATE.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(P_LANG) LIKE  DD04T-DDLANGUAGE
*"             VALUE(P_TREEAREA) LIKE  DD02D-DDTEXT
*"             VALUE(P_TREEGROUP) LIKE  DD04L-ROLLNAME
*"             VALUE(P_TREETABLE) LIKE  DD02D-TABNAME
*"       TABLES
*"              P_RETURN STRUCTURE  LISTZEILE
*"----------------------------------------------------------------------

statics pn like sy-cprog.

DATA: codetab(72) occurs 10 with header line,
      ln type i, msg(128),
      L_TABNAME LIKE DD02L-TABNAME,
      L_RC LIKE SY-SUBRC,
      lf_sap_release type i.

move sy-saprl(1) to lf_sap_release.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'T800S' AND AS4LOCAL = 'A'.
ENDSELECT.

L_RC = SY-SUBRC.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'TKA01' AND AS4LOCAL = 'A'.
ENDSELECT.

IF SY-SUBRC <> 0 OR L_RC <> 0 OR lf_sap_release > 3.
   EXIT.
ENDIF.

if PN(2) <> '%_'.
   APPEND 'REPORT ZWATN3.' TO CODETAB.
   APPEND 'FORM Z_AW_TREE_NAVIGATE_FORM' TO CODETAB.
   APPEND '       TABLES' TO CODETAB.
   APPEND '             P_RETURN STRUCTURE  LISTZEILE' TO CODETAB.
   APPEND '       USING' TO CODETAB.
   APPEND '            VALUE(P_LANG) LIKE  DD04T-DDLANGUAGE' TO CODETAB.
   APPEND '            P_TREEAREA1 LIKE  DD02D-DDTEXT' TO CODETAB.
   APPEND '            P_TREEGROUP1 LIKE  DD04L-ROLLNAME'
     TO CODETAB.
   APPEND '            P_TREETABLE1 LIKE  DD02D-TABNAME.'
     TO CODETAB.
   APPEND 'TABLES: DD02T, DD03L, DD04T.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'TABLES: TKA01, T800S, T800Y.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_TREE OCCURS 0,' TO CODETAB.
   APPEND 'NODE_NAME LIKE T800S-SETNR,' TO CODETAB.
   APPEND 'NODE_DESC LIKE DD04T-DDTEXT,' TO CODETAB.
   APPEND 'NODE_TYPE LIKE T800S-SETNR,' TO CODETAB.
   APPEND 'NODE_TABLE LIKE T800S-TAB,' TO CODETAB.
   APPEND 'TABLE_DESC LIKE DD02T-DDTEXT,' TO CODETAB.
   APPEND 'SET_TYPE LIKE T800S-TYPE.' TO CODETAB.
   APPEND 'DATA: END OF ITAB_TREE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: NO_ROWS TYPE I.' TO CODETAB.
   APPEND 'DATA: SETNAME LIKE RGSBS-SETNR,' TO CODETAB.
   APPEND '      TABNAME LIKE RGSBS-TABLE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_SUPERSETS OCCURS 0.' TO CODETAB.
   APPEND '        INCLUDE STRUCTURE SETLIST.' TO CODETAB.
   APPEND 'DATA: END OF ITAB_SUPERSETS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_HIERARCHY OCCURS 10.' TO CODETAB.
   APPEND '        INCLUDE STRUCTURE SETHIER.' TO CODETAB.
   APPEND 'DATA: END OF ITAB_HIERARCHY.' TO CODETAB.
   APPEND '' TO CODETAB.

   APPEND 'DATA:       P_TREEAREA LIKE  SETHEADER-SUBCLASS,' TO CODETAB.
   APPEND '            P_TREEGROUP LIKE  SETHEADER-FIELDNAME,'
     TO CODETAB.
   APPEND '            P_TREETABLE LIKE  SETHEADER-TABNAME.' TO CODETAB.

   APPEND '            P_TREEAREA = P_TREEAREA1.' TO CODETAB.
   APPEND '            P_TREEGROUP = P_TREEGROUP1.' TO CODETAB.
   APPEND '            P_TREETABLE = P_TREETABLE1.' TO CODETAB.

   APPEND 'ITAB_TREE-TABLE_DESC = SPACE.' TO CODETAB.
   APPEND 'IF ( P_TREEAREA = ''NULL'' ).' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '  SELECT * FROM TKA01.' TO CODETAB.
   APPEND '    ITAB_TREE-NODE_NAME = TKA01-KOKRS.' TO CODETAB.
   APPEND '    ITAB_TREE-NODE_DESC = TKA01-BEZEI.' TO CODETAB.
   APPEND '    ITAB_TREE-NODE_TYPE = ''AREA''.' TO CODETAB.
   APPEND '    ITAB_TREE-NODE_TABLE = ''NULL''.' TO CODETAB.
   APPEND '    ITAB_TREE-SET_TYPE = SPACE.' TO CODETAB.
   APPEND '    APPEND ITAB_TREE.' TO CODETAB.
   APPEND '  ENDSELECT.' TO CODETAB.
   APPEND '  ITAB_TREE-NODE_NAME = ''*''.' TO CODETAB.
   APPEND '  ITAB_TREE-NODE_DESC = ''No controlling area''.' TO CODETAB.
   APPEND '  ITAB_TREE-NODE_TYPE = ''AREA''.' TO CODETAB.
   APPEND '  ITAB_TREE-NODE_TABLE = ''NULL''.' TO CODETAB.
   APPEND '  ITAB_TREE-SET_TYPE = SPACE.' TO CODETAB.
   APPEND '  APPEND ITAB_TREE.' TO CODETAB.
   APPEND 'ELSEIF ( ( P_TREEAREA <> ''NULL'' ) and' TO CODETAB.
   APPEND '       ( P_TREEGROUP = ''NULL'' ) ).' TO CODETAB.
   APPEND '  IF ( P_TREEAREA = ''*'' ).' TO CODETAB.
   APPEND '    SELECT * FROM T800S WHERE' TO CODETAB.
   APPEND '                        SEARCHFLD = SPACE' TO CODETAB.
   APPEND '                        AND   ( TYPE = ''S'' OR' TO CODETAB.
   APPEND '                              TYPE = ''B'' ).' TO CODETAB.
   APPEND '      SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '      TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '           EXPORTING' TO CODETAB.
   APPEND '                SETNAME   = SETNAME' TO CODETAB.
   APPEND '                TABNAME   = TABNAME' TO CODETAB.
   APPEND '           TABLES' TO CODETAB.
   APPEND '                SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '           EXCEPTIONS' TO CODETAB.
   APPEND '                OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.'
     TO CODETAB.
   APPEND '      IF NO_ROWS = 0.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_NAME = T800S-FELD.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_TABLE = T800S-TAB.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_DESC = SPACE.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_TYPE = ''GROUP''.' TO CODETAB.
   APPEND '        ITAB_TREE-SET_TYPE = SPACE.' TO CODETAB.
   APPEND '        SELECT SINGLE * FROM DD02T' TO CODETAB.
   APPEND '         WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '               AND DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '               AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '               AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          ITAB_TREE-TABLE_DESC = DD02T-DDTEXT.' TO CODETAB.
   APPEND '        ELSE.' TO CODETAB.
   APPEND '        SELECT * FROM DD02T UP TO 1 ROWS' TO CODETAB.
   APPEND '         WHERE TABNAME = T800S-TAB' TO CODETAB.
*   append '               AND DDLANGUAGE = P_LANG' to codetab.
   APPEND '               AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '               AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND '        ENDSELECT.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          ITAB_TREE-TABLE_DESC = DD02T-DDTEXT.' TO CODETAB.
   APPEND '        ELSE.' TO CODETAB.
   APPEND '          CLEAR ITAB_TREE-TABLE_DESC.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '        SELECT SINGLE * FROM DD03L' TO CODETAB.
   APPEND '         WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '               AND FIELDNAME = T800S-FELD' TO CODETAB.
   APPEND '               AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '               AND AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          SELECT SINGLE * FROM DD04T' TO CODETAB.
   APPEND '           WHERE DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '             AND   ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '             AND   AS4LOCAL  = ''A''' TO CODETAB.
   APPEND '             AND   AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '          IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_DESC = DD04T-DDTEXT.' TO CODETAB.
   APPEND '          ELSE.' TO CODETAB.
   APPEND '          SELECT * FROM DD04T UP TO 1 ROWS' TO CODETAB.
*   append '           WHERE DDLANGUAGE = P_LANG' to codetab.
   APPEND '           WHERE' TO CODETAB.
*   append '             AND   ROLLNAME = DD03L-ROLLNAME' to codetab.
   APPEND '             ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '             AND   AS4LOCAL  = ''A''' TO CODETAB.
   APPEND '             AND   AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '          ENDSELECT.' TO CODETAB.
   APPEND '          IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_DESC = DD04T-DDTEXT.' TO CODETAB.
   APPEND '          ELSE.' TO CODETAB.
   APPEND '            CLEAR ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '          ENDIF.' TO CODETAB.
   APPEND '          ENDIF.' TO CODETAB.
   APPEND '          APPEND ITAB_TREE.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '    ENDSELECT.' TO CODETAB.
   APPEND '  ELSE.' TO CODETAB.
   APPEND '    SELECT SINGLE * FROM TKA01' TO CODETAB.
   APPEND '       WHERE KOKRS = P_TREEAREA.' TO CODETAB.
   APPEND '    IF ( TKA01-KTOPL <> SPACE ).' TO CODETAB.
   APPEND '      SELECT * FROM T800S' TO CODETAB.
   APPEND '         WHERE ( SEARCHFLD = TKA01-KOKRS' TO CODETAB.
   APPEND '            OR    SEARCHFLD = TKA01-KTOPL )' TO CODETAB.
   APPEND '           AND   ( TYPE = ''S'' OR TYPE = ''B'' )'
     TO CODETAB.
   APPEND '           AND   SETNR LIKE ''0H%''.' TO CODETAB.
   APPEND '        IF ( T800S-FELD <> SPACE ) AND' TO CODETAB.
   APPEND '           ( NOT ( T800S-FELD CS ''*D'' ) ).' TO CODETAB.
   APPEND '          SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '          TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '          CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '               EXPORTING' TO CODETAB.
   APPEND '                    SETNAME   = SETNAME' TO CODETAB.
   APPEND '                    TABNAME   = TABNAME' TO CODETAB.
   APPEND '               TABLES' TO CODETAB.
   APPEND '                    SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '               EXCEPTIONS' TO CODETAB.
   APPEND '                    OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '          DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.'
     TO CODETAB.
   APPEND '          IF NO_ROWS = 0.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_NAME = T800S-FELD.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_TABLE = T800S-TAB.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_DESC = SPACE.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_TYPE = ''GROUP''.' TO CODETAB.
   APPEND '            ITAB_TREE-SET_TYPE = SPACE.' TO CODETAB.
   APPEND '            SELECT SINGLE * FROM DD02T' TO CODETAB.
   APPEND '             WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '                   AND DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '                   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND '            IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '              ITAB_TREE-TABLE_DESC = DD02T-DDTEXT.'
     TO CODETAB.
   APPEND '            ELSE.' TO CODETAB.
   APPEND '            SELECT * FROM DD02T UP TO 1 ROWS' TO CODETAB.
   APPEND '             WHERE TABNAME = T800S-TAB' TO CODETAB.
*   append '                   AND DDLANGUAGE = P_LANG' to codetab.
   APPEND '                   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND '            ENDSELECT.' TO CODETAB.
   APPEND '            IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '              ITAB_TREE-TABLE_DESC = DD02T-DDTEXT.'
     TO CODETAB.
   APPEND '            ELSE.' TO CODETAB.
   APPEND '              CLEAR ITAB_TREE-TABLE_DESC.' TO CODETAB.
   APPEND '            ENDIF.' TO CODETAB.
   APPEND '            ENDIF.' TO CODETAB.
   APPEND '            SELECT SINGLE * FROM DD03L' TO CODETAB.
   APPEND '             WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '                   AND FIELDNAME = T800S-FELD' TO CODETAB.
   APPEND '                   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                   AND AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '            IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '              SELECT SINGLE * FROM DD04T' TO CODETAB.
   APPEND '               WHERE DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '                 AND   ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '                 AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                 AND   AS4VERS   = ''0000''.' TO CODETAB.
   APPEND '              IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '                ITAB_TREE-NODE_DESC = DD04T-DDTEXT.'
     TO CODETAB.
   APPEND '              ELSE.' TO CODETAB.
   APPEND '              SELECT * FROM DD04T UP TO 1 ROWS ' TO CODETAB.
*   append '               WHERE DDLANGUAGE = P_LANG' to codetab.
*  append '                 AND   ROLLNAME = DD03L-ROLLNAME' to codetab.
   APPEND '                WHERE ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '                 AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                 AND   AS4VERS   = ''0000''.' TO CODETAB.
   APPEND '              ENDSELECT.' TO CODETAB.
   APPEND '              IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '                ITAB_TREE-NODE_DESC = DD04T-DDTEXT.'
     TO CODETAB.
   APPEND '              ELSE.' TO CODETAB.
   APPEND '                CLEAR ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '              ENDIF.' TO CODETAB.
   APPEND '              ENDIF.' TO CODETAB.
   APPEND '              APPEND ITAB_TREE.' TO CODETAB.
   APPEND '            ENDIF.' TO CODETAB.
   APPEND '          ENDIF.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '      ENDSELECT.' TO CODETAB.
   APPEND '    ELSE.' TO CODETAB.
   APPEND '      SELECT * FROM T800S WHERE SEARCHFLD = TKA01-KOKRS'
     TO CODETAB.
   APPEND '                          AND   ( TYPE      = ''S'''
     TO CODETAB.
   APPEND '                                  OR TYPE = ''B'' )'
     TO CODETAB.
   APPEND '                          AND   SETNR LIKE ''0H%''.'
     TO CODETAB.
   APPEND '        IF ( T800S-FELD <> SPACE ) AND' TO CODETAB.
   APPEND '           ( NOT ( T800S-FELD CS ''*D'' ) ).' TO CODETAB.
   APPEND '          SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '          TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '          CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '               EXPORTING' TO CODETAB.
   APPEND '                    SETNAME   = SETNAME' TO CODETAB.
   APPEND '                    TABNAME   = TABNAME' TO CODETAB.
   APPEND '               TABLES' TO CODETAB.
   APPEND '                    SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '               EXCEPTIONS' TO CODETAB.
   APPEND '                    OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '          DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.'
     TO CODETAB.
   APPEND '          IF NO_ROWS = 0.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_NAME = T800S-FELD.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_TABLE = T800S-TAB.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_DESC = SPACE.' TO CODETAB.
   APPEND '            ITAB_TREE-NODE_TYPE = ''GROUP''.' TO CODETAB.
   APPEND '            ITAB_TREE-SET_TYPE = SPACE.' TO CODETAB.
   APPEND '            SELECT SINGLE * FROM DD02T' TO CODETAB.
   APPEND '             WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '                   AND DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '                   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND '            IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '              ITAB_TREE-TABLE_DESC = DD02T-DDTEXT.'
     TO CODETAB.
   APPEND '            ELSE.' TO CODETAB.
   APPEND '            SELECT * FROM DD02T UP TO 1 ROWS' TO CODETAB.
   APPEND '             WHERE TABNAME = T800S-TAB' TO CODETAB.
*   append '                   AND DDLANGUAGE = P_LANG' to codetab.
   APPEND '                   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                   AND AS4VERS = ''0000''.' TO CODETAB.
   APPEND '            ENDSELECT.' TO CODETAB.
   APPEND '            IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '              ITAB_TREE-TABLE_DESC = DD02T-DDTEXT.'
     TO CODETAB.
   APPEND '            ELSE.' TO CODETAB.
   APPEND '              CLEAR ITAB_TREE-TABLE_DESC.' TO CODETAB.
   APPEND '            ENDIF.' TO CODETAB.
   APPEND '            ENDIF.' TO CODETAB.
   APPEND '            SELECT SINGLE * FROM DD03L' TO CODETAB.
   APPEND '             WHERE TABNAME = T800S-TAB' TO CODETAB.
   APPEND '                   AND FIELDNAME = T800S-FELD' TO CODETAB.
   APPEND '                   AND AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                   AND AS4VERS  = ''0000''.' TO CODETAB.
   APPEND '            IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '              SELECT SINGLE * FROM DD04T' TO CODETAB.
   APPEND '               WHERE DDLANGUAGE = P_LANG' TO CODETAB.
   APPEND '                 AND   ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '                 AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                 AND   AS4VERS   = ''0000''.' TO CODETAB.
   APPEND '              IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '                ITAB_TREE-NODE_DESC = DD04T-DDTEXT.'
     TO CODETAB.
   APPEND '              ELSE.' TO CODETAB.
   APPEND '              SELECT * FROM DD04T UP TO 1 ROWS ' TO CODETAB.
*   append '               WHERE DDLANGUAGE = P_LANG' to codetab.
*  append '                 AND   ROLLNAME = DD03L-ROLLNAME' to codetab.
   APPEND '                WHERE ROLLNAME = DD03L-ROLLNAME' TO CODETAB.
   APPEND '                 AND   AS4LOCAL = ''A''' TO CODETAB.
   APPEND '                 AND   AS4VERS   = ''0000''.' TO CODETAB.
   APPEND '              ENDSELECT.' TO CODETAB.
   APPEND '              IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '                ITAB_TREE-NODE_DESC = DD04T-DDTEXT.'
     TO CODETAB.
   APPEND '              ELSE.' TO CODETAB.
   APPEND '                CLEAR ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '              ENDIF.' TO CODETAB.
   APPEND '              ENDIF.' TO CODETAB.
   APPEND '              APPEND ITAB_TREE.' TO CODETAB.
   APPEND '            ENDIF.' TO CODETAB.
   APPEND '          ENDIF.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '      ENDSELECT.' TO CODETAB.
   APPEND '    ENDIF.' TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND 'ELSEIF ( ( P_TREEAREA <> ''NULL'' )' TO CODETAB.
   APPEND '    and ( P_TREEGROUP <> ''NULL'' ) ).' TO CODETAB.
   APPEND '  IF ( P_TREEAREA = ''*'' ).' TO CODETAB.
   APPEND '    SELECT * FROM T800S WHERE SEARCHFLD = SPACE' TO CODETAB.
   APPEND '                        AND   FELD  = P_TREEGROUP'
     TO CODETAB.
   APPEND '                        AND   TAB  = P_TREETABLE' TO CODETAB.
   APPEND '                        AND   ( TYPE = ''S''' TO CODETAB.
   APPEND '                                OR TYPE = ''B'' ).'
     TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '      TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '           EXPORTING' TO CODETAB.
   APPEND '                SETNAME   = SETNAME' TO CODETAB.
   APPEND '                TABNAME   = TABNAME' TO CODETAB.
   APPEND '           TABLES' TO CODETAB.
   APPEND '                SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '           EXCEPTIONS' TO CODETAB.
   APPEND '                OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.'
     TO CODETAB.
   APPEND '      IF NO_ROWS = 0.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_NAME = T800S-SETNR.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_TABLE = T800S-TAB.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_TYPE = ''ROOT''.' TO CODETAB.
   APPEND '        ITAB_TREE-SET_TYPE = T800S-TYPE.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_DESC = SPACE.' TO CODETAB.
   APPEND '        SELECT SINGLE * FROM T800Y' TO CODETAB.
   APPEND '         WHERE LANGU = P_LANG' TO CODETAB.
   APPEND '           AND   TAB = T800S-TAB' TO CODETAB.
   APPEND '           AND   SETNR = T800S-SETNR.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          ITAB_TREE-NODE_DESC = T800Y-TITLE.' TO CODETAB.
   APPEND '        ELSE.' TO CODETAB.
   APPEND '        SELECT * FROM T800Y UP TO 1 ROWS' TO CODETAB.
*   append '         WHERE LANGU = P_LANG' to codetab.
*   append '           AND   TAB = T800S-TAB' to codetab.
   APPEND '          WHERE TAB = T800S-TAB' TO CODETAB.
   APPEND '           AND   SETNR = T800S-SETNR.' TO CODETAB.
   APPEND '        ENDSELECT.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          ITAB_TREE-NODE_DESC = T800Y-TITLE.' TO CODETAB.
   APPEND '        ELSE.' TO CODETAB.
   APPEND '          CLEAR ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '        APPEND ITAB_TREE.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    ENDSELECT.' TO CODETAB.
   APPEND '  ELSE.' TO CODETAB.
   APPEND '    SELECT SINGLE * FROM TKA01' TO CODETAB.
   APPEND '       WHERE KOKRS = P_TREEAREA.' TO CODETAB.
   APPEND '    SELECT * FROM T800S' TO CODETAB.
   APPEND '     WHERE FELD = P_TREEGROUP' TO CODETAB.
   APPEND '       AND   ( SEARCHFLD = P_TREEAREA' TO CODETAB.
   APPEND '        OR      SEARCHFLD = TKA01-KTOPL )' TO CODETAB.
   APPEND '       AND   TAB  = P_TREETABLE' TO CODETAB.
   APPEND '       AND   ( TYPE = ''S'' OR TYPE = ''B'' )' TO CODETAB.
   APPEND '       AND   SETNR LIKE ''0H%''.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      SETNAME = T800S-SETNR.' TO CODETAB.
   APPEND '      TABNAME = T800S-TAB.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      CALL FUNCTION ''G_SET_GET_SUPERSETS''' TO CODETAB.
   APPEND '           EXPORTING' TO CODETAB.
   APPEND '                SETNAME   = SETNAME' TO CODETAB.
   APPEND '                TABNAME   = TABNAME' TO CODETAB.
   APPEND '           TABLES' TO CODETAB.
   APPEND '                SUPERSETS = ITAB_SUPERSETS' TO CODETAB.
   APPEND '           EXCEPTIONS' TO CODETAB.
   APPEND '                OTHERS    = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '      DESCRIBE TABLE ITAB_SUPERSETS LINES NO_ROWS.'
     TO CODETAB.
   APPEND '      IF NO_ROWS = 0.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_NAME = T800S-SETNR.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_TABLE = T800S-TAB.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_TYPE = ''ROOT''.' TO CODETAB.
   APPEND '        ITAB_TREE-SET_TYPE = T800S-TYPE.' TO CODETAB.
   APPEND '        ITAB_TREE-NODE_DESC = SPACE.' TO CODETAB.
   APPEND '        SELECT SINGLE * FROM T800Y' TO CODETAB.
   APPEND '         WHERE LANGU = P_LANG' TO CODETAB.
   APPEND '           AND   TAB = T800S-TAB' TO CODETAB.
   APPEND '           AND   SETNR = T800S-SETNR.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          ITAB_TREE-NODE_DESC = T800Y-TITLE.' TO CODETAB.
   APPEND '        ELSE.' TO CODETAB.
   APPEND '        SELECT * FROM T800Y UP TO 1 ROWS ' TO CODETAB.
*   append '         WHERE LANGU = P_LANG' to codetab.
*   append '           AND   TAB = T800S-TAB' to codetab.
   APPEND '          WHERE TAB = T800S-TAB' TO CODETAB.
   APPEND '           AND   SETNR = T800S-SETNR.' TO CODETAB.
   APPEND '        ENDSELECT.' TO CODETAB.
   APPEND '        IF SY-SUBRC = 0.' TO CODETAB.
   APPEND '          ITAB_TREE-NODE_DESC = T800Y-TITLE.' TO CODETAB.
   APPEND '        ELSE.' TO CODETAB.
   APPEND '          CLEAR ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '        ENDIF.' TO CODETAB.
   APPEND '        APPEND ITAB_TREE.' TO CODETAB.
   APPEND '      ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '    ENDSELECT.' TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SORT ITAB_TREE BY NODE_TABLE NODE_NAME.' TO CODETAB.
   APPEND 'DELETE ADJACENT DUPLICATES FROM ITAB_TREE.' TO CODETAB.
   APPEND ' LOOP AT ITAB_TREE.' TO CODETAB.
   APPEND 'DATA: TDESC(60).' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '   IF ( ( ITAB_TREE-NODE_TABLE <> ''NULL'' ) AND' TO CODETAB.
   APPEND '        ( ITAB_TREE-NODE_TYPE = ''GROUP'' ) ).' TO CODETAB.
   APPEND '     IF ITAB_TREE-TABLE_DESC <> SPACE.' TO CODETAB.
   APPEND '        CONCATENATE ITAB_TREE-TABLE_DESC ''-''' TO CODETAB.
   APPEND '                    ITAB_TREE-NODE_DESC' TO CODETAB.
   APPEND '           INTO TDESC.' TO CODETAB.
   APPEND '     ELSE.' TO CODETAB.
   APPEND '        TDESC = ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '     ENDIF.' TO CODETAB.
   APPEND '     CONCATENATE' TO CODETAB.
   APPEND '     ITAB_TREE-NODE_TABLE ''-''' TO CODETAB.
   APPEND '     ITAB_TREE-NODE_NAME ''|''' TO CODETAB.
   APPEND '     TDESC ''|''' TO CODETAB.
   APPEND '     ITAB_TREE-NODE_TYPE ''|''' TO CODETAB.
   APPEND '     INTO P_RETURN-ZEILE.' TO CODETAB.
   APPEND '     CONDENSE ITAB_TREE NO-GAPS.' TO CODETAB.
   APPEND '     APPEND P_RETURN.' TO CODETAB.
   APPEND '   ELSE.' TO CODETAB.
   APPEND '     IF ITAB_TREE-TABLE_DESC <> SPACE.' TO CODETAB.
   APPEND '        CONCATENATE ITAB_TREE-TABLE_DESC' TO CODETAB.
   APPEND '                    ''-'' ITAB_TREE-NODE_DESC' TO CODETAB.
   APPEND '           INTO TDESC.' TO CODETAB.
   APPEND '     ELSE.' TO CODETAB.
   APPEND '        TDESC = ITAB_TREE-NODE_DESC.' TO CODETAB.
   APPEND '     ENDIF.' TO CODETAB.
   APPEND '     CONCATENATE' TO CODETAB.
   APPEND '     ITAB_TREE-NODE_NAME ''|''' TO CODETAB.
   APPEND '     TDESC ''|''' TO CODETAB.
   APPEND '     ITAB_TREE-NODE_TYPE ''|''' TO CODETAB.
   APPEND '     INTO P_RETURN-ZEILE.' TO CODETAB.
   APPEND '     CONDENSE ITAB_TREE NO-GAPS.' TO CODETAB.
   APPEND '     APPEND P_RETURN.' TO CODETAB.
   APPEND '   ENDIF.' TO CODETAB.
   APPEND ' ENDLOOP.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND ' P_RETURN-ZEILE = '' BusinessObjects Data Integrator''.'
     TO CODETAB.
   APPEND ' APPEND P_RETURN.' TO CODETAB.
   APPEND 'ENDFORM.' TO CODETAB.
   generate subroutine pool CODETAB name pn message msg line ln.
endif.

PERFORM Z_AW_TREE_NAVIGATE_FORM IN PROGRAM (pn)
       TABLES
             P_RETURN
       USING
             P_LANG
             P_TREEAREA
             P_TREEGROUP
             P_TREETABLE.

ENDFUNCTION.

FORM Z_AW_TREE_NAVIGATE_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
