FUNCTION Z_AW_RFC_ABAP_INSTALL_AND_RUN.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(MODE) LIKE  SY-MSGTY DEFAULT 'F'
*"             VALUE(PROGRAMNAME) LIKE  SY-REPID DEFAULT '<<RFC1>>'
*"       EXPORTING
*"             VALUE(ERRORMESSAGE) LIKE  SY-MSGV1
*"       TABLES
*"              PROGRAM STRUCTURE  PROGTAB
*"              WRITES STRUCTURE  LISTZEILE
*"----------------------------------------------------------------------

DATA: BEGIN OF LISTOBJ OCCURS 20.
       INCLUDE STRUCTURE ABAPLIST.
DATA: END OF LISTOBJ.
DATA: MESS(72), LIN(72), WRD(72).

AUTHORITY-CHECK OBJECT 'S_ADMI_FCD'
         ID 'S_ADMI_FCD' FIELD 'MEMO'.
IF SY-SUBRC <> 0.
  MESSAGE E868(SO).
ENDIF.

AUTHORITY-CHECK OBJECT 'S_DEVELOP'
         ID 'DEVCLASS' DUMMY
         ID 'OBJTYPE' FIELD 'PROG'
         ID 'OBJNAME' DUMMY
         ID 'P_GROUP' DUMMY
         ID 'ACTVT' FIELD '03'.
IF SY-SUBRC <> 0.
  MESSAGE E868(SO).
ENDIF.

IF MODE = 'F' OR MODE = 'A'.
   SYNTAX-CHECK FOR PROGRAM MESSAGE MESS LINE LIN WORD WRD.
ENDIF.

IF MESS <> SPACE.
  ERRORMESSAGE = MESS.
  EXIT.
ENDIF.

IF MODE = 'F'.
  PROGRAMNAME = '<<XRFC>>'.
  INSERT REPORT PROGRAMNAME FROM PROGRAM.
ELSEIF MODE = 'A'.
  IF PROGRAMNAME = SPACE.
     ERRORMESSAGE = 'Program name submitted from DI is empty. Exit!'.
     EXIT.
  ELSE.
     INSERT REPORT PROGRAMNAME FROM PROGRAM.
  ENDIF.
ENDIF.

SUBMIT (PROGRAMNAME) AND RETURN EXPORTING LIST TO MEMORY.

CALL FUNCTION 'LIST_FROM_MEMORY'
                            TABLES LISTOBJECT = LISTOBJ
                            EXCEPTIONS NOT_FOUND = 1.
IF SY-SUBRC = 0.

  CALL FUNCTION 'LIST_TO_ASCI'
                            TABLES LISTOBJECT = LISTOBJ
                                   LISTASCI   = WRITES.
ENDIF.
IF MODE = 'F' OR MODE = 'A'.
  DELETE REPORT PROGRAMNAME.
ENDIF.

ENDFUNCTION.

FORM Z_AW_RFC_ABAP_INSTALL_AND_RUN_ CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
