FUNCTION Z_AW_BW_QUERY.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(P_CODE) LIKE  DD01D-DATATYPE
*"             VALUE(P_IAREA) LIKE  DD01D-DDTEXT OPTIONAL
*"             VALUE(P_ICUBE) LIKE  DD01D-DDTEXT OPTIONAL
*"             VALUE(P_ODSO) LIKE  DD01D-DDTEXT OPTIONAL
*"       TABLES
*"              ENTRIES STRUCTURE  TAB512
*"----------------------------------------------------------------------

statics pn like sy-cprog.

DATA: codetab(72) occurs 10 with header line,
      ln type i, msg(128),
      L_TABNAME LIKE DD02L-TABNAME,
      L_RC LIKE SY-SUBRC,
      PN1 like sy-cprog,
      bw_ver type i.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'RSDAREA' AND AS4LOCAL = 'A'.
ENDSELECT.

L_RC = SY-SUBRC.

SELECT TABNAME INTO L_TABNAME FROM DD02L UP TO 1 ROWS
WHERE TABNAME = 'RSDCUBE' AND AS4LOCAL = 'A'.
ENDSELECT.

IF SY-SUBRC <> 0 OR L_RC <> 0.
  EXIT.
ENDIF.

if PN(2) <> '%_'.
   CLEAR PN1.
   REFRESH CODETAB.
   CLEAR CODETAB.
   APPEND 'REPORT ZAWBWQR1.' TO CODETAB.
   APPEND 'FORM Z_AW_BW_CHECK_FORM' TO CODETAB.
   APPEND 'CHANGING' TO CODETAB.
   APPEND 'VER TYPE I.' TO CODETAB.
   APPEND 'DATA lt_cvers LIKE cvers' TO CODETAB.
   APPEND ' OCCURS 0 WITH HEADER LINE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CALL FUNCTION ''TR_GET_SAPR3_TYPE'' '
 TO CODETAB.
   APPEND '     TABLES' TO CODETAB.
   APPEND '        tt_cvers       = lt_cvers'
 TO CODETAB.
   APPEND '     EXCEPTIONS' TO CODETAB.
   APPEND '        OTHERS       = 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ver = 0.' TO CODETAB.
   APPEND 'READ TABLE lt_cvers' TO CODETAB.
   APPEND ' WITH KEY component = ''SAP_BW''.'
 TO CODETAB.
   APPEND 'IF sy-subrc = 0.' TO CODETAB.
   APPEND '  move lt_cvers-release(1) to ver.'
 TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND '  READ TABLE lt_cvers' TO CODETAB.
   APPEND ' WITH KEY component = ''SAP_BIW''.'
 TO CODETAB.
   APPEND '  IF sy-subrc = 0.' TO CODETAB.
   APPEND '    move lt_cvers-release(1) to ver.'
 TO CODETAB.
   APPEND '  ENDIF.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDFORM.' TO CODETAB.
   generate subroutine pool CODETAB name pn1 message msg line ln.
   IF PN1 IS INITIAL.
     EXIT.
   ENDIF.
   bw_ver = 0.
   PERFORM Z_AW_BW_CHECK_FORM IN PROGRAM (pn1)
     CHANGING BW_VER.
   IF BW_VER < 1 OR BW_VER > 9.
     EXIT.
   ENDIF.
   REFRESH CODETAB.
   CLEAR CODETAB.
   APPEND 'REPORT  ZAWBWQRY.' TO CODETAB.
   APPEND 'TYPE-POOLS: rs, rsd, rsdq.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'TABLES: RSDAREA, RSDAREAT,' TO CODETAB.
   APPEND 'RSDCUBE, RSDCUBET, DD02L, DD02T,' TO CODETAB.
   APPEND 'RSDODSO, RSDODSOT, DD25L, DD25T.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: BEGIN OF ITAB_LINES OCCURS 0,' TO CODETAB.
   APPEND 'OBJ_TYPE(2),' TO CODETAB.
   APPEND 'NAME(128),' TO CODETAB.
   APPEND 'DESC(256),' TO CODETAB.
   APPEND 'END OF ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA INFOLINE(400) TYPE C.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA TABLE_LIST.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CONSTANTS: DELIM(1) TYPE C VALUE '','',' TO CODETAB.
   APPEND 'ACTIVE LIKE RS_C_OBJVERS-ACTIVE' TO CODETAB.
   APPEND 'VALUE RS_C_OBJVERS-ACTIVE,' TO CODETAB.
   APPEND 'TYPE_INFOAREA(2) TYPE C VALUE ''IA'',' TO CODETAB.
   APPEND 'TYPE_INFOCUBE(2) TYPE C VALUE ''IC'',' TO CODETAB.
   APPEND 'TYPE_ODS_OBJECT(2) TYPE C VALUE ''OD'',' TO CODETAB.
   APPEND 'TYPE_TABLE(2) TYPE C VALUE ''TB''.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: P_CODE LIKE  RSDCHABAS-CONVEXIT,' TO CODETAB.
   APPEND 'P_IAREA LIKE  RSDAREA-INFOAREA,' TO CODETAB.
   APPEND 'P_ICUBE LIKE  RSDCUBET-INFOCUBE,' TO CODETAB.
   APPEND 'P_ODSO LIKE  RSDODSO-ODSOBJECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM Z_AW_BW_QUERY_FORM' TO CODETAB.
   APPEND 'TABLES' TO CODETAB.
   APPEND 'ENTRIES STRUCTURE  TAB512' TO CODETAB.
   APPEND 'USING' TO CODETAB.
   APPEND 'P_CODE1 LIKE DD01D-DATATYPE' TO CODETAB.
   APPEND 'P_IAREA1 LIKE DD01D-DDTEXT' TO CODETAB.
   APPEND 'P_ICUBE1 LIKE DD01D-DDTEXT' TO CODETAB.
   APPEND 'P_ODSO1 LIKE DD01D-DDTEXT.' TO CODETAB.
   APPEND 'P_CODE = P_CODE1.' TO CODETAB.
   APPEND 'P_IAREA = P_IAREA1.' TO CODETAB.
   APPEND 'P_ICUBE = P_ICUBE1.' TO CODETAB.
   APPEND 'P_ODSO = P_ODSO1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'REFRESH ITAB_LINES.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR TABLE_LIST.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR ENTRIES.' TO CODETAB.
   APPEND 'REFRESH ENTRIES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CASE P_CODE.' TO CODETAB.
   APPEND 'WHEN ''ROOT''. " Get root objects (top-level infoareas)'
    TO CODETAB.
   APPEND 'PERFORM PROC_ROOT.' TO CODETAB.
   APPEND 'WHEN ''LSIA''. " Get (the list of all) InfoAreas' TO CODETAB.
   APPEND 'PERFORM GET_INFOAREAS.' TO CODETAB.
   APPEND 'WHEN ''LSIC''. " Get (the list of all) InfoCubes' TO CODETAB.
   APPEND 'PERFORM GET_INFOCUBES.' TO CODETAB.
   APPEND 'WHEN ''LSOD''. " Get (the list of all) ODS objects'
     TO CODETAB.
   APPEND 'PERFORM GET_ODS_OBJECTS.' TO CODETAB.
   APPEND 'WHEN ''IATB''. " Get InfoArea tables (incl. child IA tbls)'
     TO CODETAB.
   APPEND 'MOVE ''X'' TO TABLE_LIST.' TO CODETAB.
   APPEND 'PERFORM GET_INFOAREA_TABLES USING P_IAREA.' TO CODETAB.
   APPEND 'WHEN ''ICTB''. " Get InfoCube tables' TO CODETAB.
   APPEND 'MOVE ''X'' TO TABLE_LIST.' TO CODETAB.
   APPEND 'PERFORM GET_INFOCUBE_TABLES USING P_ICUBE.' TO CODETAB.
   APPEND 'WHEN ''ODTB''. "Get ODS tables' TO CODETAB.
   APPEND 'MOVE ''X'' TO TABLE_LIST.' TO CODETAB.
   APPEND 'PERFORM GET_ODS_TABLES USING P_ODSO.' TO CODETAB.
   APPEND 'WHEN ''IASO''. " Get InfoArea sub-objects' TO CODETAB.
   APPEND 'PERFORM GET_INFOAREA_SUBOBJECTS USING P_IAREA.' TO CODETAB.
   APPEND 'WHEN OTHERS. " Undefined proc. code' TO CODETAB.
   APPEND 'CLEAR INFOLINE.' TO CODETAB.
   APPEND 'ENDCASE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM WRITE_RESULTS TABLES ENTRIES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM PROC_ROOT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: D_INFOAREA_P_NULL LIKE RSDAREA-INFOAREA_P,' TO CODETAB.
   APPEND 'D_ROOT LIKE RSDAREA-INFOAREA,' TO CODETAB.
   APPEND 'D_NEXT LIKE RSDAREA-INFOAREA,' TO CODETAB.
   APPEND 'WA_AREA LIKE RSDAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR: D_ROOT, D_INFOAREA_P_NULL.' TO CODETAB.
   APPEND 'SELECT *' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = D_INFOAREA_P_NULL' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE' TO CODETAB.
   APPEND 'AND INFOAREA NOT IN' TO CODETAB.
   APPEND '( SELECT INFOAREA_N FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = D_INFOAREA_P_NULL' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE ).' TO CODETAB.
   APPEND 'D_ROOT = RSDAREA-INFOAREA.' TO CODETAB.
   APPEND 'D_NEXT = RSDAREA-INFOAREA_N.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF D_ROOT IS INITIAL.' TO CODETAB.
   IF BW_VER = 2.
     APPEND 'EXIT.' TO CODETAB.
   ELSE.
     APPEND 'RETURN.' TO CODETAB.
   ENDIF.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DO.' TO CODETAB.
   APPEND 'SELECT SINGLE * FROM RSDAREA' TO CODETAB.
   APPEND 'INTO WA_AREA' TO CODETAB.
   APPEND 'WHERE INFOAREA = D_ROOT' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'SELECT *' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'INTO WA_AREA' TO CODETAB.
   APPEND 'UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE INFOAREA = D_ROOT.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'D_ROOT = WA_AREA-INFOAREA_N.' TO CODETAB.
   APPEND 'IF RSDAREA-OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'CLEAR RSDAREAT.' TO CODETAB.
   APPEND 'SELECT * FROM RSDAREAT UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND INFOAREA = WA_AREA-INFOAREA.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_INFOAREA.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = WA_AREA-INFOAREA.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = RSDAREAT-TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES. CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'IF D_ROOT IS INITIAL.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDDO.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " PROC_ROOT' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_INFOAREAS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: D_INFOAREA_P_NULL LIKE RSDAREA-INFOAREA_P,' TO CODETAB.
   APPEND 'D_ROOT LIKE RSDAREA-INFOAREA,' TO CODETAB.
   APPEND 'D_NEXT LIKE RSDAREA-INFOAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR: D_ROOT, D_INFOAREA_P_NULL.' TO CODETAB.
   APPEND 'SELECT *' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = D_INFOAREA_P_NULL' TO CODETAB.
   APPEND 'AND OBJVERS = ''A''' TO CODETAB.
   APPEND 'AND INFOAREA NOT IN' TO CODETAB.
   APPEND '( SELECT INFOAREA_N FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = D_INFOAREA_P_NULL' TO CODETAB.
   APPEND 'AND OBJVERS = ''A'' ).' TO CODETAB.
   APPEND 'D_ROOT = RSDAREA-INFOAREA.' TO CODETAB.
   APPEND 'D_NEXT = RSDAREA-INFOAREA_N.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF D_ROOT IS INITIAL.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM PROCESS_WITH_ROOT USING D_ROOT 1.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_INFOAREAS' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_INFOCUBES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_INFOCUBE LIKE RSDCUBE-INFOCUBE,' TO CODETAB.
   APPEND 'L_TXTLG LIKE RSDCUBET-TXTLG.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT INFOCUBE' TO CODETAB.
   APPEND 'INTO L_INFOCUBE' TO CODETAB.
   APPEND 'FROM RSDCUBE' TO CODETAB.
   APPEND 'WHERE OBJVERS = ACTIVE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR L_TXTLG.' TO CODETAB.
   APPEND 'SELECT SINGLE TXTLG' TO CODETAB.
   APPEND 'INTO L_TXTLG' TO CODETAB.
   APPEND 'FROM RSDCUBET' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND INFOCUBE = L_INFOCUBE' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_INFOCUBE.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = L_INFOCUBE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES. CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_INFOCUBES' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_ODS_OBJECTS.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_ODSOBJECT LIKE RSDODSO-ODSOBJECT,' TO CODETAB.
   APPEND 'L_TXTLG LIKE RSDODSOT-TXTLG.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT ODSOBJECT' TO CODETAB.
   APPEND 'INTO L_ODSOBJECT' TO CODETAB.
   APPEND 'FROM RSDODSO' TO CODETAB.
   APPEND 'WHERE OBJVERS = ACTIVE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR L_TXTLG.' TO CODETAB.
   APPEND 'SELECT SINGLE TXTLG' TO CODETAB.
   APPEND 'INTO L_TXTLG' TO CODETAB.
   APPEND 'FROM RSDODSOT' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND ODSOBJECT = L_ODSOBJECT' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_ODS_OBJECT.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = L_ODSOBJECT.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES. CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_ODS_OBJECTS' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_INFOAREA_TABLES' TO CODETAB.
   APPEND 'USING F_INFOAREA LIKE RSDAREA-INFOAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT SINGLE *' TO CODETAB.
   APPEND 'INTO RSDAREA' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA = F_INFOAREA' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM GET_INFOAREA_TABLES1 USING F_INFOAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_INFOAREA_TABLES' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_INFOCUBE_TABLES' TO CODETAB.
   APPEND 'USING F_INFOCUBE LIKE RSDCUBE-INFOCUBE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_DESC LIKE DD02T-DDTEXT,' TO CODETAB.
   APPEND 'L_SUBRC LIKE SY-SUBRC.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CONSTANTS: lc_tabnr_1  TYPE numc1 VALUE ''0''.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA:' TO CODETAB.
   APPEND 'l_s_cube      TYPE rsd_s_cube,' TO CODETAB.
   APPEND 'l_t_dime      TYPE rsd_t_dime,' TO CODETAB.
   APPEND 'l_s_dime      TYPE rsd_s_dime,' TO CODETAB.
   APPEND 'l_t_cube_iobj TYPE rsd_t_cube_iobj,' TO CODETAB.
   APPEND 'l_t_dime_iobj TYPE rsd_t_dime_iobj,' TO CODETAB.
   APPEND 'l_t_cob_pro   TYPE rsd_t_cob_pro,' TO CODETAB.
   APPEND 'l_ts_cob_pro  TYPE rsd_ts_cob_pro,' TO CODETAB.
   APPEND 'l_tabix       LIKE sy-tabix,' TO CODETAB.
   APPEND 'l_s_dime_iobj TYPE rsd_s_dime_iobj,' TO CODETAB.
   APPEND 'l_chktab      TYPE rsd_tablnm,' TO CODETAB.
   APPEND 'l_sidtab      TYPE rsd_tablnm,' TO CODETAB.
   APPEND 'l_xtab        TYPE rsd_tablnm,' TO CODETAB.
   APPEND 'l_ytab        TYPE rsd_tablnm,' TO CODETAB.
   APPEND 'l_ptab        TYPE rsd_tablnm,' TO CODETAB.
   APPEND 'l_qtab        TYPE rsd_tablnm,' TO CODETAB.
   APPEND 'l_txtsh       TYPE rsd_s_text-txtsh,' TO CODETAB.
   APPEND 'l_chabasnm    TYPE rsd_iobjnm.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CALL FUNCTION ''RSD_CUBE_GET''' TO CODETAB.
   APPEND 'EXPORTING' TO CODETAB.
   APPEND 'i_infocube         = F_INFOCUBE' TO CODETAB.
   APPEND '*           I_OBJVERS          = ACTIVE' TO CODETAB.
   APPEND '*           I_BYPASS_BUFFER    = RS_C_FALSE' TO CODETAB.
   APPEND 'i_with_atr_nav     = RS_C_TRUE' TO CODETAB.
   APPEND 'IMPORTING' TO CODETAB.
   APPEND 'e_s_cube           = l_s_cube' TO CODETAB.
   APPEND '*           E_S_TBHD           =' TO CODETAB.
   APPEND '*           E_TBHD_NOT_FOUND   =' TO CODETAB.
   APPEND '*           E_T_CUBET          =' TO CODETAB.
   APPEND 'e_t_cube_iobj      = l_t_cube_iobj' TO CODETAB.
   APPEND '*           E_T_CUBE_DIME      =' TO CODETAB.
   APPEND 'e_t_dime           = l_t_dime' TO CODETAB.
   APPEND '*           E_T_DIMET          =' TO CODETAB.
   APPEND 'e_t_dime_iobj      = l_t_dime_iobj' TO CODETAB.
   APPEND '*           E_T_ICHA_PRO       =' TO CODETAB.
   APPEND '*           E_T_IKYF_PRO       =' TO CODETAB.
   APPEND 'EXCEPTIONS' TO CODETAB.
   APPEND 'infocube_not_found = 1' TO CODETAB.
   APPEND 'illegal_input      = 2' TO CODETAB.
   APPEND 'OTHERS             = 3.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CALL FUNCTION ''RSD_COB_PRO_ALL_GET''' TO CODETAB.
   APPEND 'EXPORTING' TO CODETAB.
   APPEND 'i_infocube                = F_INFOCUBE' TO CODETAB.
   APPEND 'i_with_atr_nav            = rs_c_true' TO CODETAB.
   APPEND '*           I_WITH_META_IOBJ  = RS_C_FALSE' TO CODETAB.
   APPEND '*           I_OBJVERS         = RS_C_OBJVERS-ACTIVE'
     TO CODETAB.
   APPEND '*           I_BYPASS_BUFFER   = RS_C_FALSE' TO CODETAB.
   APPEND 'IMPORTING' TO CODETAB.
   APPEND 'e_t_cob_pro              = l_t_cob_pro' TO CODETAB.
   APPEND '*           E_T_IOBJ_CMP              =' TO CODETAB.
   APPEND '*           E_T_ATR                   =' TO CODETAB.
   APPEND 'EXCEPTIONS' TO CODETAB.
   APPEND 'infocube_not_found        = 1' TO CODETAB.
   APPEND 'error_reading_infocatalog = 2' TO CODETAB.
   APPEND 'illegal_input             = 3' TO CODETAB.
   APPEND 'OTHERS                    = 4.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'l_ts_cob_pro = l_t_cob_pro.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_s_cube-facttab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'CLEAR: INFOLINE, ITAB_LINES-DESC.' TO CODETAB.
   APPEND 'CONCATENATE ''Fact table ('' F_INFOCUBE '') :''' TO CODETAB.
   APPEND 'L_DESC INTO ITAB_LINES-DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Dimensions' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DESCRIBE TABLE l_t_dime LINES l_tabix.' TO CODETAB.
   APPEND 'WHILE l_tabix > 0.' TO CODETAB.
   APPEND 'READ TABLE l_t_dime INDEX l_tabix INTO l_s_dime.' TO CODETAB.
   APPEND 'IF sy-subrc <> 0.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND 'SUBTRACT 1 FROM l_tabix.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_s_dime-tablnm.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR: INFOLINE, ITAB_LINES-DESC.' TO CODETAB.
   APPEND 'CONCATENATE ''Dimension'' l_s_dime-dimension' TO CODETAB.
   APPEND 'INTO INFOLINE SEPARATED BY SPACE.' TO CODETAB.
   APPEND 'CONCATENATE INFOLINE '' ('' l_s_dime-infocube '') :'''
     TO CODETAB.
   APPEND 'l_s_dime-txtlg INTO ITAB_LINES-DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDWHILE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Characteristics (no navigational attributes)' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'LOOP AT l_t_dime_iobj INTO l_s_dime_iobj' TO CODETAB.
   APPEND 'WHERE atrnavfl = rs_c_false.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM get_tables_for_iobjnm' TO CODETAB.
   APPEND 'USING    f_infocube' TO CODETAB.
   APPEND 'l_s_dime_iobj-iobjnm' TO CODETAB.
   APPEND 'l_ts_cob_pro' TO CODETAB.
   APPEND 'CHANGING l_chktab' TO CODETAB.
   APPEND 'l_sidtab' TO CODETAB.
   APPEND 'l_xtab' TO CODETAB.
   APPEND 'l_ytab' TO CODETAB.
   APPEND 'l_ptab' TO CODETAB.
   APPEND 'l_qtab' TO CODETAB.
   APPEND 'l_txtsh.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '*   SID table' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_sidtab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'IF ITAB_LINES-NAME <> L_DESC.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'ELSE.' TO CODETAB.
   APPEND 'CONCATENATE ''SID Table for''' TO CODETAB.
   APPEND 'l_s_dime_iobj-iobjnm' TO CODETAB.
   APPEND 'INTO ITAB_LINES-DESC SEPARATED BY SPACE.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF NOT l_xtab IS INITIAL.' TO CODETAB.
   APPEND '*     X-Table' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_xtab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF NOT l_xtab IS INITIAL.' TO CODETAB.
   APPEND '*     Y-Table' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_ytab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '*   Master table View' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_chktab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF NOT l_ptab IS INITIAL.' TO CODETAB.
   APPEND '*     P-Table' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_ptab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF NOT l_qtab IS INITIAL.' TO CODETAB.
   APPEND '*     Q-Table' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_qtab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDLOOP.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Characteristics (with navigational attributes)' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'LOOP AT l_t_dime_iobj INTO l_s_dime_iobj' TO CODETAB.
   APPEND 'WHERE atrnavfl = rs_c_true.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM get_tables_for_iobjnm' TO CODETAB.
   APPEND 'USING    f_infocube' TO CODETAB.
   APPEND 'l_s_dime_iobj-iobjnm' TO CODETAB.
   APPEND 'l_ts_cob_pro' TO CODETAB.
   APPEND 'CHANGING l_chktab' TO CODETAB.
   APPEND 'l_sidtab' TO CODETAB.
   APPEND 'l_xtab' TO CODETAB.
   APPEND 'l_ytab' TO CODETAB.
   APPEND 'l_ptab' TO CODETAB.
   APPEND 'l_qtab' TO CODETAB.
   APPEND 'l_txtsh.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM get_owner_for_navattr' TO CODETAB.
   APPEND 'USING    f_infocube' TO CODETAB.
   APPEND 'l_s_dime_iobj-iobjnm' TO CODETAB.
   APPEND 'l_ts_cob_pro' TO CODETAB.
   APPEND 'CHANGING l_chabasnm.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_chktab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF NOT l_sidtab IS INITIAL.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = l_sidtab.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDLOOP.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_INFOCUBE_TABLES' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_ODS_TABLES' TO CODETAB.
   APPEND 'USING F_ODS LIKE RSDODSO-ODSOBJECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_DESC LIKE DD02T-DDTEXT,' TO CODETAB.
   APPEND 'L_SUBRC LIKE SY-SUBRC.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CONSTANTS lc_tabnr_1' TO CODETAB.
   APPEND 'TYPE numc1 VALUE ''0''.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: l_logsys TYPE logsys,' TO CODETAB.
   APPEND 'l_nspacegen TYPE namespace,' TO CODETAB.
   APPEND 'l_name_o TYPE rs_char30,' TO CODETAB.
   APPEND 'e_tablnm LIKE dd02l-tabname.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CALL FUNCTION' TO CODETAB.
   APPEND '''RSA_LOGICAL_SYSTEM_BIW_GET''' TO CODETAB.
   APPEND 'EXPORTING' TO CODETAB.
   APPEND 'i_without_popup = rs_c_true' TO CODETAB.
   APPEND 'IMPORTING' TO CODETAB.
   APPEND 'e_logsys_biw    = l_logsys' TO CODETAB.
   APPEND 'EXCEPTIONS' TO CODETAB.
   APPEND 'OTHERS          = 3.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '*   get generate prefix from name' TO CODETAB.
   APPEND 'CALL FUNCTION' TO CODETAB.
   APPEND '''RSD_NSPACE_PAR_GET_FROM_NAME''' TO CODETAB.
   APPEND 'EXPORTING' TO CODETAB.
   APPEND 'i_objnm           = F_ODS' TO CODETAB.
   APPEND 'IMPORTING' TO CODETAB.
   APPEND 'e_nspacegen       = l_nspacegen' TO CODETAB.
   APPEND 'e_name_w_o_prefix = l_name_o' TO CODETAB.
   APPEND 'EXCEPTIONS' TO CODETAB.
   APPEND 'name_error        = 1.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* build tables names' TO CODETAB.
   APPEND 'CONCATENATE l_nspacegen' TO CODETAB.
   APPEND 'rsd_c_id_tablnm_for_ods' TO CODETAB.
   APPEND 'l_name_o' TO CODETAB.
   APPEND 'rsdod_c_tabt-active' TO CODETAB.
   APPEND 'lc_tabnr_1' TO CODETAB.
   APPEND 'INTO e_tablnm.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = e_tablnm.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE' TO CODETAB.
   APPEND 'USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CONCATENATE l_nspacegen' TO CODETAB.
   APPEND 'rsd_c_id_tablnm_for_ods l_name_o' TO CODETAB.
   APPEND 'rsdod_c_tabt-modified lc_tabnr_1' TO CODETAB.
   APPEND 'INTO e_tablnm.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = e_tablnm.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CONCATENATE l_nspacegen' TO CODETAB.
   APPEND 'rsd_c_id_tablnm_for_ods l_name_o' TO CODETAB.
   IF BW_VER = 2.
     APPEND 'rsdod_c_tabt-change_log lc_tabnr_1' TO CODETAB.
   ELSE.
     APPEND 'rsdod_c_tabt-update lc_tabnr_1' TO CODETAB.
   ENDIF.
   APPEND 'INTO e_tablnm.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = e_tablnm.' TO CODETAB.
   APPEND 'PERFORM CHECK_TABLE USING ITAB_LINES-NAME' TO CODETAB.
   APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
   APPEND 'IF L_SUBRC = 0.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   IF BW_VER > 2.
     APPEND 'CONCATENATE l_nspacegen' TO CODETAB.
     APPEND 'rsd_c_id_tablnm_for_ods l_name_o' TO CODETAB.
     APPEND 'rsdod_c_tabt-rollback lc_tabnr_1' TO CODETAB.
     APPEND 'INTO e_tablnm.' TO CODETAB.
     APPEND 'ITAB_LINES-NAME = e_tablnm.' TO CODETAB.
     APPEND 'PERFORM CHECK_TABLE USING ITAB_LINES-NAME' TO CODETAB.
     APPEND 'CHANGING L_DESC L_SUBRC.' TO CODETAB.
     APPEND 'IF L_SUBRC = 0.' TO CODETAB.
     APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_TABLE.' TO CODETAB.
     APPEND 'ITAB_LINES-DESC = L_DESC.' TO CODETAB.
     APPEND 'APPEND ITAB_LINES.' TO CODETAB.
     APPEND 'ENDIF.' TO CODETAB.
     APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
     APPEND '' TO CODETAB.
   ENDIF.
   APPEND 'ENDFORM. " GET_ODS_TABLES' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_INFOAREA_SUBOBJECTS' TO CODETAB.
   APPEND 'USING F_INFOAREA LIKE RSDAREA-INFOAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_INFOAREA LIKE RSDAREA-INFOAREA,' TO CODETAB.
   APPEND 'L_INFOCUBE LIKE RSDCUBE-INFOCUBE,' TO CODETAB.
   APPEND 'L_ODSOBJECT LIKE RSDODSO-ODSOBJECT,' TO CODETAB.
   APPEND 'L_TXTLG LIKE RSDCUBET-TXTLG.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT SINGLE *' TO CODETAB.
   APPEND 'INTO RSDAREA' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA = F_INFOAREA' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Get infoareas' TO CODETAB.
   APPEND 'SELECT INFOAREA' TO CODETAB.
   APPEND 'INTO L_INFOAREA' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = F_INFOAREA' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'CLEAR RSDAREAT.' TO CODETAB.
   APPEND 'SELECT * FROM RSDAREAT UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND INFOAREA = L_INFOAREA.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = L_INFOAREA.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_INFOAREA.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = RSDAREAT-TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Get infocubes' TO CODETAB.
   APPEND 'SELECT INFOCUBE' TO CODETAB.
   APPEND 'INTO L_INFOCUBE' TO CODETAB.
   APPEND 'FROM RSDCUBE' TO CODETAB.
   APPEND 'WHERE OBJVERS = ACTIVE' TO CODETAB.
   APPEND 'AND INFOAREA = F_INFOAREA.' TO CODETAB.
   APPEND 'CLEAR L_TXTLG.' TO CODETAB.
   APPEND 'SELECT SINGLE TXTLG' TO CODETAB.
   APPEND 'INTO L_TXTLG' TO CODETAB.
   APPEND 'FROM RSDCUBET' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND INFOCUBE = L_INFOCUBE' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = L_INFOCUBE.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_INFOCUBE.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Get ODS objects' TO CODETAB.
   APPEND 'SELECT ODSOBJECT' TO CODETAB.
   APPEND 'INTO L_ODSOBJECT' TO CODETAB.
   APPEND 'FROM RSDODSO' TO CODETAB.
   APPEND 'WHERE OBJVERS = ACTIVE' TO CODETAB.
   APPEND 'AND INFOAREA = F_INFOAREA.' TO CODETAB.
   APPEND 'CLEAR L_TXTLG.' TO CODETAB.
   APPEND 'SELECT SINGLE TXTLG' TO CODETAB.
   APPEND 'INTO L_TXTLG' TO CODETAB.
   APPEND 'FROM RSDODSOT' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND ODSOBJECT = L_ODSOBJECT' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = L_ODSOBJECT.' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_ODS_OBJECT.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = L_TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES.' TO CODETAB.
   APPEND 'CLEAR ITAB_LINES.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_INFOAREA_SUBOBJECTS' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM PROCESS_WITH_ROOT' TO CODETAB.
   APPEND 'USING VALUE(P_NEXT) LIKE RSDAREA-INFOAREA' TO CODETAB.
   APPEND 'P_LEVEL.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_LEVEL TYPE I,' TO CODETAB.
   APPEND 'WA_AREA LIKE RSDAREA,' TO CODETAB.
   APPEND 'WA_AREA1 LIKE RSDAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DO.' TO CODETAB.
   APPEND 'SELECT SINGLE * FROM RSDAREA' TO CODETAB.
   APPEND 'INTO WA_AREA' TO CODETAB.
   APPEND 'WHERE INFOAREA = P_NEXT' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'IF SY-SUBRC <> 0.' TO CODETAB.
   APPEND 'SELECT *' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'INTO WA_AREA' TO CODETAB.
   APPEND 'UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE INFOAREA = P_NEXT.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'P_NEXT = WA_AREA-INFOAREA_N.' TO CODETAB.
   APPEND 'IF RSDAREA-OBJVERS = ACTIVE.' TO CODETAB.
   APPEND 'CLEAR RSDAREAT.' TO CODETAB.
   APPEND 'SELECT * FROM RSDAREAT UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE LANGU = SY-LANGU' TO CODETAB.
   APPEND 'AND INFOAREA = WA_AREA-INFOAREA.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE = TYPE_INFOAREA.' TO CODETAB.
   APPEND 'ITAB_LINES-NAME = WA_AREA-INFOAREA.' TO CODETAB.
   APPEND 'ITAB_LINES-DESC = RSDAREAT-TXTLG.' TO CODETAB.
   APPEND 'APPEND ITAB_LINES. CLEAR ITAB_LINES.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'L_LEVEL = P_LEVEL + 1.' TO CODETAB.
   APPEND 'CLEAR WA_AREA1-INFOAREA.' TO CODETAB.
   APPEND 'SELECT *' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'INTO WA_AREA1' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = WA_AREA-INFOAREA' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE' TO CODETAB.
   APPEND 'AND INFOAREA NOT IN' TO CODETAB.
   APPEND '( SELECT INFOAREA_N FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = WA_AREA-INFOAREA' TO CODETAB.
   APPEND 'AND OBJVERS = ACTIVE ).' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'IF NOT WA_AREA1-INFOAREA IS INITIAL.' TO CODETAB.
   APPEND 'PERFORM PROCESS_WITH_ROOT' TO CODETAB.
   APPEND 'USING WA_AREA1-INFOAREA L_LEVEL.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'IF P_NEXT IS INITIAL.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND 'ENDDO.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " PROCESS_WITH_ROOT' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM CHECK_TABLE USING F_NAME LIKE ITAB_LINES-NAME'
     TO CODETAB.
   APPEND 'CHANGING F_DESC LIKE DD02T-DDTEXT' TO CODETAB.
   APPEND 'F_SUBRC LIKE SY-SUBRC.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'F_SUBRC = 1.' TO CODETAB.
   APPEND 'CLEAR F_DESC.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT VIEWNAME' TO CODETAB.
   APPEND 'INTO DD25L-VIEWNAME' TO CODETAB.
   APPEND 'FROM DD25L' TO CODETAB.
   APPEND 'UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE VIEWNAME = F_NAME' TO CODETAB.
   APPEND 'AND AS4LOCAL = ACTIVE.' TO CODETAB.
   APPEND 'F_SUBRC = 0.' TO CODETAB.
   APPEND 'SELECT DDTEXT' TO CODETAB.
   APPEND 'INTO F_DESC' TO CODETAB.
   APPEND 'FROM DD25T' TO CODETAB.
   APPEND 'UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE VIEWNAME = F_NAME' TO CODETAB.
   APPEND 'AND DDLANGUAGE = SY-LANGU' TO CODETAB.
   APPEND 'AND AS4LOCAL = ACTIVE.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF F_SUBRC <> 0.' TO CODETAB.
   APPEND 'SELECT TABNAME' TO CODETAB.
   APPEND 'INTO DD02L-TABNAME' TO CODETAB.
   APPEND 'FROM DD02L' TO CODETAB.
   APPEND 'UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE TABNAME = F_NAME' TO CODETAB.
   APPEND 'AND AS4LOCAL = ACTIVE.' TO CODETAB.
   APPEND 'F_SUBRC = 0.' TO CODETAB.
   APPEND 'SELECT DDTEXT' TO CODETAB.
   APPEND 'INTO F_DESC' TO CODETAB.
   APPEND 'FROM DD02T' TO CODETAB.
   APPEND 'UP TO 1 ROWS' TO CODETAB.
   APPEND 'WHERE TABNAME = F_NAME' TO CODETAB.
   APPEND 'AND DDLANGUAGE = SY-LANGU' TO CODETAB.
   APPEND 'AND AS4LOCAL = ACTIVE.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF F_DESC IS INITIAL.' TO CODETAB.
   APPEND 'F_DESC = F_NAME.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " CHECK_TABLE' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM get_tables_for_iobjnm' TO CODETAB.
   APPEND 'USING    i_datatarget TYPE rsddatatarget' TO CODETAB.
   APPEND 'i_iobjnm     TYPE rsd_iobjnm' TO CODETAB.
   APPEND 'i_ts_cob_pro TYPE rsd_ts_cob_pro' TO CODETAB.
   APPEND 'CHANGING e_chktab     TYPE rsd_tablnm' TO CODETAB.
   APPEND 'e_sidtab     TYPE rsd_tablnm' TO CODETAB.
   APPEND 'e_xtab       TYPE rsd_tablnm' TO CODETAB.
   APPEND 'e_ytab       TYPE rsd_tablnm' TO CODETAB.
   APPEND 'e_ptab       TYPE rsd_tablnm' TO CODETAB.
   APPEND 'e_qtab       TYPE rsd_tablnm' TO CODETAB.
   APPEND 'e_txtsh      TYPE rsd_s_text-txtsh.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA:' TO CODETAB.
   APPEND 'l_s_cob_pro TYPE rsd_s_cob_pro.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'READ TABLE i_ts_cob_pro' TO CODETAB.
   IF BW_VER = 2.
     APPEND 'WITH TABLE KEY infocube = i_datatarget' TO CODETAB.
   ELSE.
     APPEND 'WITH TABLE KEY infoprov = i_datatarget' TO CODETAB.
   ENDIF.
   APPEND 'iobjnm   = i_iobjnm' TO CODETAB.
   APPEND 'INTO l_s_cob_pro.' TO CODETAB.
   APPEND 'IF sy-subrc <> 0.' TO CODETAB.
   APPEND 'EXIT.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'e_txtsh    = l_s_cob_pro-txtsh.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CALL FUNCTION ''RSD_CHKTAB_GET_FOR_CHA_BAS''' TO CODETAB.
   APPEND 'EXPORTING' TO CODETAB.
   APPEND 'i_chabasnm = l_s_cob_pro-chabasnm' TO CODETAB.
   APPEND 'IMPORTING' TO CODETAB.
   APPEND 'e_chktab   = e_chktab' TO CODETAB.
   APPEND 'e_chntab   = e_ptab' TO CODETAB.
   APPEND 'e_chttab   = e_qtab' TO CODETAB.
   APPEND 'e_sidtab   = e_sidtab' TO CODETAB.
   APPEND 'e_asitab   = e_xtab' TO CODETAB.
   APPEND 'e_asttab   = e_ytab' TO CODETAB.
   APPEND 'EXCEPTIONS' TO CODETAB.
   APPEND 'name_error = 1' TO CODETAB.
   APPEND 'OTHERS     = 2.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " get_tables_for_iobjnm' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM get_owner_for_navattr' TO CODETAB.
   APPEND 'USING   i_datatarget TYPE rsddatatarget' TO CODETAB.
   APPEND 'i_iobjnm     TYPE rsd_iobjnm' TO CODETAB.
   APPEND 'i_ts_cob_pro TYPE rsd_ts_cob_pro' TO CODETAB.
   APPEND 'CHANGING e_ochabasnm  TYPE rsd_iobjnm.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA:' TO CODETAB.
   APPEND 'l_attrinm   TYPE rsd_iobjnm,' TO CODETAB.
   APPEND 'l_chanm     TYPE rsd_iobjnm,' TO CODETAB.
   APPEND 'l_s_cob_pro TYPE rsd_s_cob_pro.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CALL FUNCTION' TO CODETAB.
   APPEND '''RSD_ATTRINM_GET_FROM_ATRNAVNM''' TO CODETAB.
   APPEND 'EXPORTING' TO CODETAB.
   APPEND 'i_atrnavnm = i_iobjnm' TO CODETAB.
   APPEND 'IMPORTING' TO CODETAB.
   APPEND 'e_attrinm  = l_attrinm' TO CODETAB.
   APPEND 'e_chanm    = l_chanm.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'READ TABLE i_ts_cob_pro' TO CODETAB.
   APPEND 'WITH TABLE KEY' TO CODETAB.
   IF BW_VER = 2.
     APPEND 'infocube = i_datatarget' TO CODETAB.
   ELSE.
     APPEND 'infoprov = i_datatarget' TO CODETAB.
   ENDIF.
   APPEND 'iobjnm   = l_chanm' TO CODETAB.
   APPEND 'INTO l_s_cob_pro.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'e_ochabasnm = l_s_cob_pro-chabasnm.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " get_owner_for_navattr' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM GET_INFOAREA_TABLES1' TO CODETAB.
   APPEND 'USING VALUE(P_NEXT) LIKE RSDAREA-INFOAREA.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Get infocube and ODS object' TO CODETAB.
   APPEND '* tables for this infoarea' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'DATA: L_INFOAREA LIKE RSDAREA-INFOAREA,' TO CODETAB.
   APPEND 'L_ICUBE LIKE RSDCUBE-INFOCUBE,' TO CODETAB.
   APPEND 'L_ODSO LIKE RSDODSO-ODSOBJECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT INFOCUBE' TO CODETAB.
   APPEND 'INTO L_ICUBE' TO CODETAB.
   APPEND 'FROM RSDCUBE' TO CODETAB.
   APPEND 'WHERE OBJVERS = ACTIVE' TO CODETAB.
   APPEND 'AND INFOAREA = P_NEXT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM GET_INFOCUBE_TABLES USING L_ICUBE.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDSELECT. " infocubes' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT ODSOBJECT' TO CODETAB.
   APPEND 'INTO L_ODSO' TO CODETAB.
   APPEND 'FROM RSDODSO' TO CODETAB.
   APPEND 'WHERE OBJVERS = ACTIVE' TO CODETAB.
   APPEND 'AND INFOAREA = P_NEXT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'PERFORM GET_ODS_TABLES USING L_ODSO.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDSELECT. "ODS objects' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND '* Get tables for all child InfoAreas' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'SELECT INFOAREA' TO CODETAB.
   APPEND 'INTO L_INFOAREA' TO CODETAB.
   APPEND 'FROM RSDAREA' TO CODETAB.
   APPEND 'WHERE INFOAREA_P = P_NEXT' TO CODETAB.
   APPEND 'AND OBJVERS = ''A''.' TO CODETAB.
   APPEND 'PERFORM GET_INFOAREA_TABLES1' TO CODETAB.
   APPEND 'USING L_INFOAREA.' TO CODETAB.
   APPEND 'ENDSELECT.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'ENDFORM. " GET_INFOAREA_TABLES1' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'FORM WRITE_RESULTS' TO CODETAB.
   APPEND 'TABLES F_ENTRIES STRUCTURE TAB512.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'IF NOT TABLE_LIST IS INITIAL.' TO CODETAB.
   APPEND 'SORT ITAB_LINES.' TO CODETAB.
   APPEND 'DELETE ADJACENT DUPLICATES FROM ITAB_LINES.' TO CODETAB.
   APPEND 'ENDIF.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'CLEAR INFOLINE.' TO CODETAB.
   APPEND 'LOOP AT ITAB_LINES.' TO CODETAB.
   APPEND 'CONCATENATE' TO CODETAB.
   APPEND 'ITAB_LINES-OBJ_TYPE' TO CODETAB.
   APPEND 'DELIM ITAB_LINES-NAME' TO CODETAB.
   APPEND 'DELIM ITAB_LINES-DESC' TO CODETAB.
   APPEND 'INTO INFOLINE.' TO CODETAB.
   APPEND 'F_ENTRIES-WA = INFOLINE.' TO CODETAB.
   APPEND 'APPEND F_ENTRIES.' TO CODETAB.
   APPEND 'CLEAR F_ENTRIES.' TO CODETAB.
   APPEND 'ENDLOOP.' TO CODETAB.
   APPEND '' TO CODETAB.
   APPEND 'F_ENTRIES-WA = ''** end **''.' TO CODETAB.
   APPEND 'APPEND F_ENTRIES.' TO CODETAB.
   APPEND 'CLEAR F_ENTRIES.' TO CODETAB.
   APPEND 'ENDFORM. " WRITE_RESULTS' TO CODETAB.
   generate subroutine pool CODETAB name pn message msg line ln.
endif.

PERFORM Z_AW_BW_QUERY_FORM IN PROGRAM (pn)
  TABLES
      ENTRIES
  USING
     P_CODE
     P_IAREA
     P_ICUBE
     P_ODSO.

ENDFUNCTION.

FORM Z_AW_BW_QUERY_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
