FUNCTION Z_AW_COLUMN_SEARCH.
*"----------------------------------------------------------------------
*"*"Local interface:
*"       IMPORTING
*"             VALUE(P_TNAME) LIKE  DD03VT-DDTEXT
*"             VALUE(P_CNAME) LIKE  DD03VT-DDTEXT
*"             VALUE(P_CDESC) LIKE  DD03VT-DDTEXT
*"             VALUE(P_LANG) LIKE  DD03VT-DDLANGUAGE
*"             VALUE(P_MAXROWS) LIKE  SY-TABIX
*"       TABLES
*"              P_RETURN STRUCTURE  LISTZEILE
*"----------------------------------------------------------------------

TABLES: DD03VT.

DATA: BEGIN OF TRANSP_TAB OCCURS 0,
       TABNAME LIKE DD02L-TABNAME.
DATA: END OF TRANSP_TAB.

SELECT * FROM DD02L
WHERE TABCLASS = 'TRANSP' AND AS4LOCAL = 'A'.

   MOVE DD02L-TABNAME TO TRANSP_TAB-TABNAME.
   APPEND TRANSP_TAB.

ENDSELECT.

IF  P_TNAME = SPACE
AND P_CNAME = SPACE
AND P_CDESC <> SPACE.

   TRANSLATE P_CDESC USING '+_*%'.

   SELECT * FROM DD03VT
            UP TO P_MAXROWS ROWS
            FOR ALL ENTRIES IN TRANSP_TAB
            WHERE DDLANGUAGE = P_LANG
            AND   TABNAME = TRANSP_TAB-TABNAME
            AND   DDTEXT LIKE P_CDESC.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ELSEIF P_TNAME = SPACE
   AND P_CDESC = SPACE
   AND P_CNAME <> SPACE.

   TRANSLATE P_CNAME USING '+_*%'.

   SELECT * FROM DD03VT
            UP TO P_MAXROWS ROWS
            FOR ALL ENTRIES IN TRANSP_TAB
            WHERE DDLANGUAGE = P_LANG
            AND   TABNAME = TRANSP_TAB-TABNAME
            AND   FIELDNAME LIKE P_CNAME.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ELSEIF P_CNAME = SPACE
   AND P_CDESC = SPACE
   AND P_TNAME <> SPACE.

   TRANSLATE P_TNAME USING '+_*%'.

   SELECT * FROM DD03VT
            UP TO P_MAXROWS ROWS
            WHERE DDLANGUAGE = P_LANG
            AND   TABNAME LIKE P_TNAME.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ELSEIF P_TNAME <> SPACE
   AND P_CNAME <> SPACE
   AND P_CDESC = SPACE.

   TRANSLATE P_CNAME USING '+_*%'.
   TRANSLATE P_TNAME USING '+_*%'.

   SELECT * FROM DD03VT
            UP TO P_MAXROWS ROWS
            WHERE DDLANGUAGE = P_LANG
            AND   TABNAME LIKE P_TNAME
            AND   FIELDNAME LIKE P_CNAME.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ELSEIF P_TNAME <> SPACE
   AND P_CNAME = SPACE
   AND P_CDESC <> SPACE.

   TRANSLATE P_CDESC USING '+_*%'.
   TRANSLATE P_TNAME USING '+_*%'.

   SELECT * FROM DD03VT
           UP TO P_MAXROWS ROWS
           WHERE DDLANGUAGE = P_LANG
           AND   TABNAME LIKE P_TNAME
           AND   FIELDNAME LIKE P_CNAME.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ELSEIF P_TNAME = SPACE
   AND P_CNAME <> SPACE
   AND P_CDESC <> SPACE.

   TRANSLATE P_CDESC USING '+_*%'.
   TRANSLATE P_CNAME USING '+_*%'.

   SELECT * FROM DD03VT
            UP TO P_MAXROWS ROWS
            FOR ALL ENTRIES IN TRANSP_TAB
            WHERE DDLANGUAGE = P_LANG
            AND   TABNAME = TRANSP_TAB-TABNAME
            AND   FIELDNAME LIKE P_CNAME
            AND   DDTEXT LIKE P_CDESC.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ELSE.

   SELECT * FROM DD03VT
            UP TO P_MAXROWS ROWS
            FOR ALL ENTRIES IN TRANSP_TAB
            WHERE TABNAME = TRANSP_TAB-TABNAME.

    CONCATENATE
    DD03VT-TABNAME '|' DD03VT-FIELDNAME '|' DD03VT-DDTEXT '|'
    INTO P_RETURN-ZEILE.

    APPEND P_RETURN.

   ENDSELECT.

ENDIF.

ENDFUNCTION.

FORM Z_AW_COLUMN_SEARCH_GETV CHANGING VERSION TYPE C.

VERSION = '6.5.1.0'.

ENDFORM.
